---
title: "Annual Figures CERP"
author: "ELevine"
date: "`r Sys.Date()`"
output: 
  word_document: 
    reference_docx: Monthly-Reports-template.docx
    fig_caption: yes
params:
  Start_date: "2024-01-01" #Start date of reporting quarter
  End_date: "2024-12-30"   #End date of reporting quarter
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
#
Estuary_code <- c("CR", "SL", "LX")
Start_date <- as.Date(params$Start_date)
End_date <- as.Date(params$End_date)

#Packages
if (!require("pacman")) {install.packages("pacman")}
#p_unlock()
pacman::p_load(odbc, DBI, dbplyr,
  tidyverse, dplyr,  stringr, #DF manipulation
  DT, openxlsx,         #Excel
  lubridate, zoo,         #Dates
  knitr, kableExtra, scales, gt, gtExtras, ggpubr, ggpattern, magick, 
  install = TRUE)
```

```{r FigureFormatting, include = FALSE}
#
East_sites <- c("SLN", "SLS", "SLC", "LXN", "LXS")
West_Sites <- c("CRE", "CRW")
#
#Shared formatting for figure consistency
BaseForm <- theme_classic() +
  theme(panel.border = element_rect(color = "black", fill = NA), #Add border
        axis.title = element_text(family = "serif", color = "black", size = 17), axis.title.x = element_text(margin = margin(t = 12)), #Adjust axis title and text
        axis.text = element_text(family = "serif", color = "black", size = 12), 
        axis.line = element_line(color = "black"),
        axis.ticks.length.x = unit(0.10, "cm"),
        axis.ticks.length.y = unit(0.15, "cm"))

East_legend <- theme(legend.position = "inside", legend.position.inside = c(.155, .995), legend.justification = c("right", "top"), legend.box.just = "right", legend.box.spacing = unit(0.15, "lines"), #Adjust legend position
                     legend.background = element_rect(color = "black", fill = "white", linetype = "solid"),
                     legend.title = element_blank(), legend.key.height = unit(0.7, "lines"), legend.key.spacing.y = unit(0.25, "lines"),
                     legend.key.width = unit(1.5, "lines"), #Adjust legend title and spacing
                     legend.text = element_text(family = "serif", color = "black", size = 12))

West_legend <- theme(legend.position = "inside", legend.position.inside = c(0.005, .980), legend.justification = c("left", "top"), legend.box.just = "left", legend.box.spacing = unit(0.25, "lines"), #Adjust legend position
                     legend.background = element_rect(color = "black", fill = "white", linetype = "solid"),
                     legend.title = element_blank(), legend.key.height = unit(0.7, "lines"), legend.key.spacing.y = unit(0.25, "lines"),
                     legend.key.width = unit(1.5, "lines"), #Adjust legend title and spacing
                     legend.text = element_text(family = "serif", color = "black", size = 12, margin = margin(r = 6, l = 5)))

FacetForm <- theme(strip.placement = "outside", strip.text.x.top = element_text(vjust = 1, hjust = 0, size = 13, family = "serif"), strip.clip = "off", panel.spacing.y = unit(0.5, "lines"), strip.background = element_blank())

PlotTitle <- theme(plot.title = element_text(size = 13, family = "serif", margin = margin(b = 0.07, t = 0.025)))

#Color and shape to station number - East
Stat_pal <- c(rgb(0, 0, 228, maxColorValue = 255), rgb(245, 0, 0, maxColorValue = 255), rgb(0, 118, 0, maxColorValue = 255))
Stations_E <- c("1" = "Station 1", "2" = "Station 2", "3" = "Station 3") 
Station_fill_E <- scale_fill_manual("", labels = Stations_E, values = setNames(Stat_pal, 1:3), na.value = "#999999")
Station_color_E <- scale_color_manual("", labels = Stations_E, values = setNames(Stat_pal, 1:3), na.value = "#999999")
Station_shape_E <- scale_shape_manual("",labels = Stations_E, values = setNames(c(21, 25, 22), 1:3))

#Color and shape to station number - West
Stat_pal2 <- c(rgb(0, 0, 228, maxColorValue = 255), rgb(245, 0, 0, maxColorValue = 255), rgb(0, 0, 228, maxColorValue = 255), rgb(245, 0, 0, maxColorValue = 255))
Stations_W <- c("1" = "Peppertree Pointe", "2" = "Iona Cove", "3" = "Bird Island", "4" = "Kitchel Key") 
Station_fill_W <- scale_fill_manual("", labels = Stations_W, values = setNames(Stat_pal2, 1:4), na.value = "#999999")
Station_color_W <- scale_color_manual("", labels = Stations_W, values = setNames(Stat_pal2, 1:4), na.value = "#999999")
Station_shape_W <- scale_shape_manual("",labels = Stations_W, values = setNames(c(21, 25, 21, 25), 1:4))

#Color to Stage
Stat_pal3 <- c(rgb(255, 255, 255, maxColorValue = 255), rgb(153, 255, 255, maxColorValue = 255), rgb(0, 0, 255, maxColorValue = 255), rgb(0, 0, 102, maxColorValue = 255))
Stages <- c("Ind" = "Indifferent", "Dev" = "Developing", "Rip" = "Ripe/Spawning", "Spe" = "Spent/Recyling") 
Stage_fill <- scale_fill_manual("", labels = Stages, values = Stat_pal3, na.value = "#999999")
#
#Cage formatting
Cage_sites <- c("SLC", "LXN", "CRE", "CRW")
Stations_cages <- c("SLC" = "St. Lucie-Central Station 1", "LXN" = "Loxahatchee-North Station 2", "CRE" = "Caloosahatchee River - Iona Cove", "CRW" = "Caloosahatchee River - Bird Island")
Cages_fill <- scale_fill_manual("", labels = Stations_cages, values = Stat_pal2, na.value = "#999999")
Cages_color <- scale_color_manual("", labels = Stations_cages, values = Stat_pal2, na.value = "#999999")

```

```{r Data gather from summary file, include=FALSE}
###Water Quality
#salinity
WQ_Sal_s <-  readWorkbook("WQ_Summary_Data.xlsx", sheet = 'Salinity Station', detectDates = TRUE, check.names = TRUE) %>% dplyr::select(starts_with(Estuary_code))
SLC_Flow <- readWorkbook("../DBHYDRO/Shared_data/SL_Flow.xlsx", sheet = 'SLESum', detectDates = TRUE, check.names = TRUE) %>% filter(Date >= Start_date & Date <= End_date)
LRE_Flow <- readWorkbook("../DBHYDRO/Shared_data/LX_Flow.xlsx", sheet = 'LOXSum', detectDates = TRUE, check.names = TRUE) %>% filter(Date >= Start_date & Date <= End_date)
CRE_Flow <- readWorkbook("../DBHYDRO/Shared_data/CR_Flow.xlsx", sheet = 'S79', detectDates = TRUE, check.names = TRUE) %>% filter(Date >= Start_date & Date <= End_date)
#Temperature
WQ_Tem_s <-  readWorkbook("WQ_Summary_Data.xlsx", sheet = 'Temp Station', detectDates = TRUE, check.names = TRUE) %>% dplyr::select(starts_with(Estuary_code))
#DO
WQ_DO_s <-  readWorkbook("WQ_Summary_Data.xlsx", sheet = 'DO Station', detectDates = TRUE, check.names = TRUE) %>% dplyr::select(starts_with(Estuary_code))
#pH
WQ_pH_s <-  readWorkbook("WQ_Summary_Data.xlsx", sheet = 'pH Station', detectDates = TRUE, check.names = TRUE) %>% dplyr::select(starts_with(Estuary_code))
#WQ_Secchi_s <-  readWorkbook("WQ_Summary_Data.xlsx", sheet = 'Secchi Station', detectDates = TRUE, check.names = TRUE)
#
#Counts_df <- readWorkbook("Summary_Data.xlsx", sheet = 'DeadRatio Station', detectDates = TRUE, check.names = TRUE)
#SH_df <- readWorkbook("Summary_Data.xlsx", sheet = 'SH Station', detectDates = TRUE, check.names = TRUE)
#Dermo_df <- readWorkbook("Summary_Data.xlsx", sheet = 'Dermo Station', detectDates = TRUE, check.names = TRUE)
#Rcrt_df <- readWorkbook("Summary_Data.xlsx", sheet = 'Rcrt Station', detectDates = TRUE, check.names = TRUE)
#Repro_df <- readWorkbook("Summary_Data.xlsx", sheet = 'Repro', detectDates = TRUE, check.names = TRUE)
#Cage_df <- readWorkbook("Summary_Data.xlsx", sheet = 'SH Mort Site', detectDates = TRUE, check.names = TRUE)
```

```{r Water Quality Data selection and cleaning}
#
##Salinity
names(WQ_Sal_s) <- gsub("\\.", "", names(WQ_Sal_s))
#
Sal_SLC_1 <- WQ_Sal_s %>% dplyr::select(contains("SL")) %>% filter(SLC_RetDate_Sal > Start_date & SLC_RetDate_Sal < End_date) %>% dplyr::select(-SLN_RetDate_Sal, -SLS_RetDate_Sal) %>% rename("SL_RetDate" = SLC_RetDate_Sal)
Sal_SLC_2 <- Sal_SLC_1 %>% gather(SiteStation, Salinity, -SL_RetDate) %>% rename("RetDate" = SL_RetDate) %>% mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("SLN", "SLS", "SLC")), Station = as.factor(substr(SiteStation, 4, 4))) %>% rbind(data.frame(RetDate = NA, SiteStation = 'SLC4_Flow', Salinity = NA, Site = 'SLN',   Station = '4', stringsAsFactors = TRUE)) #Add legend placeholder for Flow data
#
Sal_LRE_1 <- WQ_Sal_s %>% dplyr::select(contains("LX")) %>% filter(LXN_RetDate_Sal > Start_date & LXN_RetDate_Sal < End_date) %>% dplyr::select(-LXS_RetDate_Sal) %>% rename("LX_RetDate" = LXN_RetDate_Sal)
Sal_LRE_2 <- Sal_LRE_1 %>% gather(SiteStation, Salinity, -LX_RetDate) %>% rename("RetDate" = LX_RetDate) %>% mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("LXN", "LXS")), Station = as.factor(substr(SiteStation, 4, 4))) %>% rbind(data.frame(RetDate = NA, SiteStation = 'LXN4_Flow', Salinity = NA, Site = 'LXN',   Station = '4', stringsAsFactors = TRUE)) %>% rbind(data.frame(RetDate = NA, SiteStation = 'LXS4_Flow', Salinity = NA, Site = 'LXS',   Station = '4', stringsAsFactors = TRUE)) #Add legend placeholder for Flow data
#
Sal_CRE_1 <- WQ_Sal_s %>% dplyr::select(contains("CR")) %>% filter(CRE_RetDate_Sal > Start_date & CRE_RetDate_Sal < End_date) %>% dplyr::select(-CRW_RetDate_Sal) %>% rename("CR_RetDate" = CRE_RetDate_Sal)
Sal_CRE_2 <- Sal_CRE_1 %>% gather(SiteStation, Salinity, -CR_RetDate) %>% rename("RetDate" = CR_RetDate) %>% mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("CRE", "CRW")), Station = as.factor(substr(SiteStation, 4, 4))) %>% rbind(data.frame(RetDate = NA, SiteStation = 'CRE4_Flow', Salinity = NA, Site = 'CRE',   Station = '5', stringsAsFactors = TRUE)) #Add legend placeholder for Flow data
#
#
#Flow - Need data for each site for plotting
SLC_Flow_2 <- rbind(SLC_Flow %>% dplyr::select(Date, SLESum) %>% mutate(Site = "SLN"), 
                    SLC_Flow %>% dplyr::select(Date, SLESum) %>% mutate(Site = "SLS")) %>%
  rbind(SLC_Flow %>% dplyr::select(Date, SLESum) %>% mutate(Site = "SLC")) %>% 
  mutate(Rescale = (SLESum - min(SLESum))/(max(SLESum) - min(SLESum))*(40-0)+0) #Rescale flow to salinity axis limits for plotting
#
LRE_Flow_2 <- LRE_Flow %>% dplyr::select(-Analysis_Date, -LOXSum) %>% gather(Site, Flow, -Estuary, -Date) %>% mutate(Site = case_when(Site == "LOX_Flow" ~ "LXN", TRUE ~ "LXS")) %>% mutate(Rescale = (Flow - min(Flow))/(max(Flow) - min(Flow))*(40-0)+0) #Rescale flow to salinity axis limits for plotting
#
CRE_Flow_2 <-  rbind(CRE_Flow %>% dplyr::select(Date, Flow) %>% mutate(Site = "CRE"), 
                    CRE_Flow %>% dplyr::select(Date, Flow) %>% mutate(Site = "CRW")) %>% 
  mutate(Rescale = (Flow - min(Flow))/(max(Flow) - min(Flow))*(38-0)+0) #Rescale flow to salinity axis limits for plotting
#
#
##Temperature
names(WQ_Tem_s) <- gsub("\\.", "", names(WQ_Tem_s))
#
Tem_SLC_1 <- WQ_Tem_s %>% dplyr::select(contains("SL")) %>% filter(SLC_RetDate_Temp > Start_date & SLC_RetDate_Temp < End_date) %>% dplyr::select(-SLN_RetDate_Temp, -SLS_RetDate_Temp) %>% rename("SL_RetDate" = SLC_RetDate_Temp)
Tem_SLC_2 <- Tem_SLC_1 %>% gather(SiteStation, Temperature, -SL_RetDate) %>% rename("RetDate" = SL_RetDate) %>% mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("SLN", "SLS", "SLC")), Station = as.factor(substr(SiteStation, 4, 4)))
#
Tem_LRE_1 <- WQ_Tem_s %>% dplyr::select(contains("LX")) %>% filter(LXN_RetDate_Temp > Start_date & LXN_RetDate_Temp < End_date) %>% dplyr::select(-LXS_RetDate_Temp) %>% rename("LX_RetDate" = LXN_RetDate_Temp)
Tem_LRE_2 <- Tem_LRE_1 %>% gather(SiteStation, Temperature, -LX_RetDate) %>% rename("RetDate" = LX_RetDate) %>% mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("LXN", "LXS")), Station = as.factor(substr(SiteStation, 4, 4)))
#
Tem_CRE_1 <- WQ_Tem_s %>% dplyr::select(contains("CR")) %>% filter(CRE_RetDate_Temp > Start_date & CRE_RetDate_Temp < End_date) %>% dplyr::select(-CRW_RetDate_Temp) %>% rename("CR_RetDate" = CRE_RetDate_Temp)
Tem_CRE_2 <- Tem_CRE_1 %>% gather(SiteStation, Temperature, -CR_RetDate) %>% rename("RetDate" = CR_RetDate) %>% mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("CRE", "CRW")), Station = as.factor(substr(SiteStation, 4, 4)))
#
#
##DO
names(WQ_DO_s) <- gsub("\\.", "", names(WQ_DO_s))
#
DO_SLC_1 <- WQ_DO_s %>% dplyr::select(contains("SL")) %>% filter(SLC_RetDate_DO > Start_date & SLC_RetDate_DO < End_date) %>% dplyr::select(-SLN_RetDate_DO, -SLS_RetDate_DO) %>% rename("SL_RetDate" = SLC_RetDate_DO)
DO_SLC_2 <- DO_SLC_1 %>% gather(SiteStation, DO, -SL_RetDate) %>% rename("RetDate" = SL_RetDate) %>% mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("SLN", "SLS", "SLC")), Station = as.factor(substr(SiteStation, 4, 4)))
#
DO_LRE_1 <- WQ_DO_s %>% dplyr::select(contains("LX")) %>% filter(LXN_RetDate_DO > Start_date & LXN_RetDate_DO < End_date) %>% dplyr::select(-LXS_RetDate_DO) %>% rename("LX_RetDate" = LXN_RetDate_DO)
DO_LRE_2 <- DO_LRE_1 %>% gather(SiteStation, DO, -LX_RetDate) %>% rename("RetDate" = LX_RetDate) %>% mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("LXN", "LXS")), Station = as.factor(substr(SiteStation, 4, 4)))
#
DO_CRE_1 <- WQ_DO_s %>% dplyr::select(contains("CR")) %>% filter(CRE_RetDate_DO > Start_date & CRE_RetDate_DO < End_date) %>% dplyr::select(-CRW_RetDate_DO) %>% rename("CR_RetDate" = CRE_RetDate_DO)
DO_CRE_2 <- DO_CRE_1 %>% gather(SiteStation, DO, -CR_RetDate) %>% rename("RetDate" = CR_RetDate) %>% mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("CRE", "CRW")), Station = as.factor(substr(SiteStation, 4, 4)))
#
#
##pH
names(WQ_pH_s) <- gsub("\\.", "", names(WQ_pH_s))
#
pH_SLC_1 <- WQ_pH_s %>% dplyr::select(contains("SL")) %>% filter(SLC_RetDate_pH > Start_date & SLC_RetDate_pH < End_date) %>% dplyr::select(-SLN_RetDate_pH, -SLS_RetDate_pH) %>% rename("SL_RetDate" = SLC_RetDate_pH)
pH_SLC_2 <- pH_SLC_1 %>% gather(SiteStation, pH, -SL_RetDate) %>% rename("RetDate" = SL_RetDate) %>% mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("SLN", "SLS", "SLC")), Station = as.factor(substr(SiteStation, 4, 4)))
#
pH_LRE_1 <- WQ_pH_s %>% dplyr::select(contains("LX")) %>% filter(LXN_RetDate_pH > Start_date & LXN_RetDate_pH < End_date) %>% dplyr::select(-LXS_RetDate_pH) %>% rename("LX_RetDate" = LXN_RetDate_pH)
pH_LRE_2 <- pH_LRE_1 %>% gather(SiteStation, pH, -LX_RetDate) %>% rename("RetDate" = LX_RetDate) %>% mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("LXN", "LXS")), Station = as.factor(substr(SiteStation, 4, 4)))
#
pH_CRE_1 <- WQ_pH_s %>% dplyr::select(contains("CR")) %>% filter(CRE_RetDate_pH > Start_date & CRE_RetDate_pH < End_date) %>% dplyr::select(-CRW_RetDate_pH) %>% rename("CR_RetDate" = CRE_RetDate_pH)
pH_CRE_2 <- pH_CRE_1 %>% gather(SiteStation, pH, -CR_RetDate) %>% rename("RetDate" = CR_RetDate) %>% mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("CRE", "CRW")), Station = as.factor(substr(SiteStation, 4, 4)))
#
```

The following figures are presented for the annual report covering `r Start_date %>% format("%B %Y")` through `r End_date %>% format("%B %Y")`.
\newpage

```{r SLC Salinity Figure, fig.cap = "**Figure 2.**  Monthly salinity recorded in 2024 at stations in the St. Lucie-North (top), St. Lucie-South (middle), and St. Lucie-Central (bottom) study sites and the sum of the mean daily flow rate at S80, S97, S49, and Gordy Rd structures as downloaded from the South Florida Water Management District’s DBHydro site.", fig.height = 10, fig.width = 8, fig.fullwidth=TRUE}
#max(SLC_Flow_2$SLESum) - round to nearest divisible by 4
ggarrange(
  #SLN
  ggplot() +
    geom_area(data = SLC_Flow_2 %>% filter(Site == "SLN"), aes(Date, Rescale), fill = rgb(156, 156, 156, maxColorValue = 255))+
    geom_line(data = Sal_SLC_2 %>% filter(Site == "SLN"), aes(RetDate, Salinity, color = Station), linewidth = 0.7) +
    geom_point(data = Sal_SLC_2 %>% filter(Site == "SLN"), aes(RetDate, Salinity, fill = Station, shape = Station), size = 2.75) +
    labs(title = "St. Lucie-North") +
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("Salinity", expand = c(0,0), sec.axis = sec_axis(~.*(4800/40), name = "Flow (cfc)", breaks = seq(0,4800, 1200))) +
    coord_cartesian(ylim = c(0, 40))+
    scale_fill_manual("", labels = c("1" = "Station 1", "2" = "Station 2", "3" = "Station 3", "4" = "Flow"), values = c("1" = rgb(0, 0, 228, maxColorValue = 255), "2" = rgb(245, 0, 0, maxColorValue = 255), "3" = rgb(0, 118, 0, maxColorValue = 255), "4" = rgb(156, 156, 156, maxColorValue = 255)), breaks = c("4", "1", "2", "3")) +
    scale_color_manual("", labels = c("1" = "Station 1", "2" = "Station 2", "3" = "Station 3", "4" = "Flow"), values = c("1" = rgb(0, 0, 228, maxColorValue = 255), "2" = rgb(245, 0, 0, maxColorValue = 255), "3" = rgb(0, 118, 0, maxColorValue = 255), "4" = "white"), breaks = c("4", "1", "2", "3")) + 
    scale_shape_manual("", labels = c("1" = "Station 1", "2" = "Station 2", "3" = "Station 3", "4" = "Flow"), values = c("1" = 21, "2" = 21, "3" = 21, "4" = 22), breaks = c("4", "1", "2", "3"))+
    BaseForm + FacetForm + West_legend + PlotTitle,
  NULL,
  #SLS
  ggplot() +
    geom_area(data = SLC_Flow_2 %>% filter(Site == "SLS"), aes(Date, Rescale), fill = rgb(156, 156, 156, maxColorValue = 255))+
    geom_line(data = Sal_SLC_2 %>% filter(Site == "SLS"), aes(RetDate, Salinity, color = Station), linewidth = 0.7) +
    geom_point(data = Sal_SLC_2 %>% filter(Site == "SLS"), aes(RetDate, Salinity, fill = Station, shape = Station), size = 2.75) +
    labs(title = "St. Lucie-South") +
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("Salinity", expand = c(0,0), sec.axis = sec_axis(~.*(4800/40), name = "Flow (cfc)", breaks = seq(0,4800, 1200))) +
    coord_cartesian(ylim = c(0, 40))+
    scale_fill_manual("", labels = c("1" = "Station 1", "2" = "Station 2", "3" = "Station 3", "4" = "Flow"), values = c("1" = rgb(0, 0, 228, maxColorValue = 255), "2" = rgb(245, 0, 0, maxColorValue = 255), "3" = rgb(0, 118, 0, maxColorValue = 255), "4" = rgb(156, 156, 156, maxColorValue = 255)), breaks = c("4", "1", "2", "3")) +
    scale_color_manual("", labels = c("1" = "Station 1", "2" = "Station 2", "3" = "Station 3", "4" = "Flow"), values = c("1" = rgb(0, 0, 228, maxColorValue = 255), "2" = rgb(245, 0, 0, maxColorValue = 255), "3" = rgb(0, 118, 0, maxColorValue = 255), "4" = "white"), breaks = c("4", "1", "2", "3")) + 
    scale_shape_manual("", labels = c("1" = "Station 1", "2" = "Station 2", "3" = "Station 3", "4" = "Flow"), values = c("1" = 21, "2" = 21, "3" = 21, "4" = 22), breaks = c("4", "1", "2", "3"))+
    BaseForm + FacetForm + PlotTitle + theme(legend.position = "none"),
  NULL,
  #SLC
  ggplot() +
    geom_area(data = SLC_Flow_2 %>% filter(Site == "SLC"), aes(Date, Rescale), fill = rgb(156, 156, 156, maxColorValue = 255))+
    geom_line(data = Sal_SLC_2 %>% filter(Site == "SLC"), aes(RetDate, Salinity, color = Station), linewidth = 0.7) +
    geom_point(data = Sal_SLC_2 %>% filter(Site == "SLC"), aes(RetDate, Salinity, fill = Station, shape = Station), size = 2.75) +
    labs(title = "St. Lucie-Central") +
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("Salinity", expand = c(0,0), sec.axis = sec_axis(~.*(4800/40), name = "Flow (cfc)", breaks = seq(0,4800, 1200))) +
    coord_cartesian(ylim = c(0, 40))+
    scale_fill_manual("", labels = c("1" = "Station 1", "2" = "Station 2", "3" = "Station 3", "4" = "Flow"), values = c("1" = rgb(0, 0, 228, maxColorValue = 255), "2" = rgb(245, 0, 0, maxColorValue = 255), "3" = rgb(0, 118, 0, maxColorValue = 255), "4" = rgb(156, 156, 156, maxColorValue = 255)), breaks = c("4", "1", "2", "3")) +
    scale_color_manual("", labels = c("1" = "Station 1", "2" = "Station 2", "3" = "Station 3", "4" = "Flow"), values = c("1" = rgb(0, 0, 228, maxColorValue = 255), "2" = rgb(245, 0, 0, maxColorValue = 255), "3" = rgb(0, 118, 0, maxColorValue = 255), "4" = "white"), breaks = c("4", "1", "2", "3")) + 
    scale_shape_manual("", labels = c("1" = "Station 1", "2" = "Station 2", "3" = "Station 3", "4" = "Flow"), values = c("1" = 21, "2" = 21, "3" = 21, "4" = 22), breaks = c("4", "1", "2", "3"))+
    BaseForm + FacetForm + PlotTitle + theme(legend.position = "none"),
  nrow =  5, heights = c(1, -0.05, 1, -0.05, 1))
#
```

```{r LRE Salinity Figure, fig.cap = "**Figure 3.**  Monthly salinity recorded in 2024 at stations in the Loxahatchee-North (top) and Loxahatchee-South (bottom) study sites and the sum of the mean daily flow rate at the Lainhart Dam and S46 structures as downloaded from the South Florida Water Management District’s DBHydro site.", fig.height = 7, fig.width = 8, fig.fullwidth=TRUE}
#max((LRE_Flow_2 %>% filter(Site == "LXN))$Flow) - round to nearest divisible by 4 -1200
ggarrange(
  #LNX
  ggplot() +
    geom_area(data = LRE_Flow_2 %>% filter(Site == "LXN"), aes(Date, Rescale*3.45), fill = rgb(156, 156, 156, maxColorValue = 255))+
    geom_line(data = Sal_LRE_2 %>% filter(Site == "LXN"), aes(RetDate, Salinity, color = Station), linewidth = 0.7) +
    geom_point(data = Sal_LRE_2 %>% filter(Site == "LXN"), aes(RetDate, Salinity, fill = Station, shape = Station), size = 2.75) +
    labs(title = "Loxahatchee-North") +
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("Salinity", expand = c(0,0), sec.axis = sec_axis(~.*(300/40), name = "Flow (cfc)", breaks = seq(0,300, 75))) +
    coord_cartesian(ylim = c(0, 40))+
    scale_fill_manual("", labels = c("1" = "Station 1", "2" = "Station 2", "3" = "Station 3", "4" = "Flow: Lainhart Dam"), values = c("1" = rgb(0, 0, 228, maxColorValue = 255), "2" = rgb(245, 0, 0, maxColorValue = 255), "3" = rgb(0, 118, 0, maxColorValue = 255), "4" = rgb(156, 156, 156, maxColorValue = 255)), breaks = c("4", "1", "2", "3")) +
    scale_color_manual("", labels = c("1" = "Station 1", "2" = "Station 2", "3" = "Station 3", "4" = "Flow: Lainhart Dam"), values = c("1" = rgb(0, 0, 228, maxColorValue = 255), "2" = rgb(245, 0, 0, maxColorValue = 255), "3" = rgb(0, 118, 0, maxColorValue = 255), "4" = "white"), breaks = c("4", "1", "2", "3")) + 
    scale_shape_manual("", labels = c("1" = "Station 1", "2" = "Station 2", "3" = "Station 3", "4" = "Flow: Lainhart Dam"), values = c("1" = 21, "2" = 21, "3" = 21, "4" = 22), breaks = c("4", "1", "2", "3"))+
    BaseForm + FacetForm + West_legend + PlotTitle,
  NULL,
  #LXS
  ggplot() +
    geom_area(data = LRE_Flow_2 %>% filter(Site == "LXS"), aes(Date, Rescale), fill = rgb(156, 156, 156, maxColorValue = 255))+
    geom_line(data = Sal_LRE_2 %>% filter(Site == "LXS"), aes(RetDate, Salinity, color = Station), linewidth = 0.7) +
    geom_point(data = Sal_LRE_2 %>% filter(Site == "LXS"), aes(RetDate, Salinity, fill = Station, shape = Station), size = 2.75) +
    labs(title = "Loxahatchee-South") +
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("Salinity", expand = c(0,0), sec.axis = sec_axis(~.*(1200/40), name = "Flow (cfc)", breaks = seq(0,1200, 300))) +
    coord_cartesian(ylim = c(0, 40))+
    scale_fill_manual("", labels = c("1" = "Station 1", "2" = "Station 2", "3" = "Station 3", "4" = "Flow: S46"), values = c("1" = rgb(0, 0, 228, maxColorValue = 255), "2" = rgb(245, 0, 0, maxColorValue = 255), "3" = rgb(0, 118, 0, maxColorValue = 255), "4" = rgb(156, 156, 156, maxColorValue = 255)), breaks = c("4", "1", "2", "3")) +
    scale_color_manual("", labels = c("1" = "Station 1", "2" = "Station 2", "3" = "Station 3", "4" = "Flow: S46"), values = c("1" = rgb(0, 0, 228, maxColorValue = 255), "2" = rgb(245, 0, 0, maxColorValue = 255), "3" = rgb(0, 118, 0, maxColorValue = 255), "4" = "white"), breaks = c("4", "1", "2", "3")) + 
    scale_shape_manual("", labels = c("1" = "Station 1", "2" = "Station 2", "3" = "Station 3", "4" = "Flow: S46"), values = c("1" = 21, "2" = 21, "3" = 21, "4" = 22), breaks = c("4", "1", "2", "3"))+
    BaseForm + FacetForm + West_legend + PlotTitle,
  nrow = 3, heights = c(1, -0.05, 1))
#
#
```

```{r CRE Salinity Figure, fig.cap = "**Figure 4.**  Monthly salinity recorded in 2024 at stations in the Caloosahatchee-East (top) and Caloosahatchee-West (bottom) study sites and the mean daily flow rate at the S79 structures as downloaded from the South Florida Water Management District’s DBHydro site.", fig.height = 7, fig.width = 8, fig.fullwidth=TRUE}
#max(CRE_Flow_2$Flow) - round to nearest divisible by 4 - 12569 > 13000, 3250
ggarrange(
  #CRE plot
  ggplot() +
    geom_area(data = CRE_Flow_2 %>% filter(Site == "CRE"), aes(Date, Rescale), fill = rgb(156, 156, 156, maxColorValue = 255))+
    geom_line(data = Sal_CRE_2 %>% filter(Station != "3" & Station != "4"), aes(RetDate, Salinity, color = Station), linewidth = 0.7) +
    geom_point(data = Sal_CRE_2 %>% filter(Station != "3" & Station != "4"), aes(RetDate, Salinity, fill = Station, shape = Station), size = 2.75) +
    labs(title = "Caloosahatchee-East") +
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("Salinity", expand = c(0,0), sec.axis = sec_axis(~.*(13000/40), name = "Flow (cfc)", breaks = seq(0,13000, 3250))) +
    coord_cartesian(ylim = c(0, 40))+
    scale_fill_manual("", labels = c("1" = "Peppertree Pointe", "2" = "Iona Cove", "3" = "Bird Island", "4" = "Kitchel Key", "5" = "Flow"), values = c("1" = rgb(0, 0, 228, maxColorValue = 255), "2" = rgb(245, 0, 0, maxColorValue = 255), "3" = rgb(0, 0, 228, maxColorValue = 255), "4" = rgb(245, 0, 0, maxColorValue = 255), "5" = rgb(156, 156, 156, maxColorValue = 255)), breaks = c("5", "1", "2", "3", "4")) +
    scale_color_manual("", labels = c("1" = "Peppertree Pointe", "2" = "Iona Cove", "3" = "Bird Island", "4" = "Kitchel Key", "5" = "Flow"), values = c("1" = rgb(0, 0, 228, maxColorValue = 255), "2" = rgb(245, 0, 0, maxColorValue = 255), "3" = rgb(0, 0, 228, maxColorValue = 255), "4" = rgb(245, 0, 0, maxColorValue = 255), "5" = "white"), breaks = c("5", "1", "2", "3", "4")) + 
    scale_shape_manual("", labels = c("1" = "Peppertree Pointe", "2" = "Iona Cove", "3" = "Bird Island", "4" = "Kitchel Key", "5" = "Flow"), values = c("1" = 21, "2" = 21, "3" = 21, "4" = 21, "5" = 22), breaks = c("5", "1", "2", "3", "4"))+ BaseForm + FacetForm + West_legend + PlotTitle,
  NULL, 
  #CRW plot
  ggplot() +
    geom_area(data = CRE_Flow_2 %>% filter(Site == "CRW"), aes(Date, Rescale), fill = rgb(156, 156, 156, maxColorValue = 255))+
    geom_line(data = Sal_CRE_2 %>% filter(Station != "1" & Station != "2"), aes(RetDate, Salinity, color = Station), linewidth = 0.7) +
    geom_point(data = Sal_CRE_2 %>% filter(Station != "1" & Station != "2"), aes(RetDate, Salinity, fill = Station, shape = Station), size = 2.75) +
    labs(title = "Caloosahatchee-West") + 
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("Salinity", expand = c(0,0), sec.axis = sec_axis(~.*(13000/40), name = "Flow (cfc)", breaks = seq(0,13000, 3250))) +
    coord_cartesian(ylim = c(0, 40))+
    scale_fill_manual("", labels = c("1" = "Peppertree Pointe", "2" = "Iona Cove", "3" = "Bird Island", "4" = "Kitchel Key", "5" = "Flow"), values = c("1" = rgb(0, 0, 228, maxColorValue = 255), "2" = rgb(245, 0, 0, maxColorValue = 255), "3" = rgb(0, 0, 228, maxColorValue = 255), "4" = rgb(245, 0, 0, maxColorValue = 255), "5" = rgb(156, 156, 156, maxColorValue = 255)), breaks = c("5", "1", "2", "3", "4")) +
    scale_color_manual("", labels = c("1" = "Peppertree Pointe", "2" = "Iona Cove", "3" = "Bird Island", "4" = "Kitchel Key", "5" = "Flow"), values = c("1" = rgb(0, 0, 228, maxColorValue = 255), "2" = rgb(245, 0, 0, maxColorValue = 255), "3" = rgb(0, 0, 228, maxColorValue = 255), "4" = rgb(245, 0, 0, maxColorValue = 255), "5" = "white"), breaks = c("5", "1", "2", "3", "4")) + 
    scale_shape_manual("", labels = c("1" = "Peppertree Pointe", "2" = "Iona Cove", "3" = "Bird Island", "4" = "Kitchel Key", "5" = "Flow"), values = c("1" = 21, "2" = 21, "3" = 21, "4" = 21, "5" = 22), breaks = c("5", "1", "2", "3", "4"))+ BaseForm + FacetForm + West_legend + PlotTitle,
  nrow = 3, heights = c(1, -0.05, 1))
#
#
```

```{r SLC Temperature Figure, fig.cap = "**Figure 5.**  Monthly water temperature recorded in 2024 at stations in the St. Lucie-North (top), St. Lucie-South (middle), and St. Lucie-Central (bottom) study sites.", fig.height = 10, fig.width = 8, fig.fullwidth=TRUE}
#
ggarrange(
  #SLN plot
  ggplot() +
    geom_line(data = Tem_SLC_2 %>% filter(Site == "SLN"), aes(RetDate, Temperature, color = Station), linewidth = 0.7)+
    geom_point(data = Tem_SLC_2 %>% filter(Site == "SLN"), aes(RetDate, Temperature, fill = Station), size = 3.25, shape = 21) +
    labs(title = "St. Lucie-North") +
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("Temperature (\u00B0C)", expand = c(0,0), limits = c(0, 40)) +
    BaseForm + FacetForm + West_legend + Station_color_E + Station_fill_E + PlotTitle,
  NULL,
  #SLS plot
  ggplot() +
    geom_line(data = Tem_SLC_2 %>% filter(Site == "SLS"), aes(RetDate, Temperature, color = Station), linewidth = 0.7)+
    geom_point(data = Tem_SLC_2 %>% filter(Site == "SLS"), aes(RetDate, Temperature, fill = Station), size = 3.25, shape = 21) +
    labs(title = "St. Lucie-South") +     
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("Temperature (\u00B0C)", expand = c(0,0), limits = c(0, 40)) +
    BaseForm + FacetForm + Station_color_E + Station_fill_E + PlotTitle + theme(legend.position = "none"),
  NULL,
  #SLC plot
  ggplot() +
    geom_line(data = Tem_SLC_2 %>% filter(Site == "SLC"), aes(RetDate, Temperature, color = Station), linewidth = 0.7)+
    geom_point(data = Tem_SLC_2 %>% filter(Site == "SLC"), aes(RetDate, Temperature, fill = Station), size = 3.25, shape = 21) +
    labs(title = "St. Lucie-Central") +     
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("Temperature (\u00B0C)", expand = c(0,0), limits = c(0, 40)) +
    BaseForm + FacetForm + Station_color_E + Station_fill_E + PlotTitle  + theme(legend.position = "none"),
  nrow = 5, heights = c(1, -0.05, 1, -0.05, 1))
#
#
```

```{r LRE Temperature Figure, fig.cap = "**Figure 6.**  Monthly water temperature recorded in 2024 at stations in the Loxahatchee-North (top) and Loxahatchee-South (bottom) study sites.", fig.height = 7, fig.width = 8, fig.fullwidth=TRUE}
#
ggarrange(
  #LXN plot
  ggplot() +
   geom_line(data = Tem_LRE_2 %>% filter(Site == "LXN"), aes(RetDate, Temperature, color = Station), linewidth = 0.7) +
    geom_point(data = Tem_LRE_2 %>% filter(Site == "LXN"), aes(RetDate, Temperature, fill = Station), size = 3.25, shape = 21) +
    labs(title = "Loxahatchee-North") +
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("Temperature (\u00B0C)", expand = c(0,0), limits = c(0, 40)) +
    BaseForm + FacetForm + West_legend + Station_color_E + Station_fill_E + PlotTitle,
  NULL,
  #LXS plot
  ggplot() +
    geom_line(data = Tem_LRE_2 %>% filter(Site == "LXS"), aes(RetDate, Temperature, color = Station), linewidth = 0.7) +
    geom_point(data = Tem_LRE_2 %>% filter(Site == "LXS"), aes(RetDate, Temperature, fill = Station), size = 3.25, shape = 21) +
    labs(title = "Loxahatchee-South") +     
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("Temperature (\u00B0C)", expand = c(0,0), limits = c(0, 40)) +
    BaseForm + FacetForm + Station_color_E + Station_fill_E + PlotTitle + theme(legend.position = "none"),
  nrow = 3, heights = c(1, -0.05, 1))
#
#
```

```{r CRE Temperature Figure, fig.cap = "**Figure 7.**  Monthly water temperature recorded in 2024 at stations in the Caloosahatchee-East (top) and Caloosahatchee-West (bottom) study sites.", fig.height = 7, fig.width = 8, fig.fullwidth=TRUE}
#
ggarrange(
  #CRE plot
  ggplot() +
   geom_line(data = Tem_CRE_2 %>% filter(Station != "3" & Station != "4"), aes(RetDate, Temperature, color = Station), linewidth = 0.7) +
    geom_point(data = Tem_CRE_2 %>% filter(Station != "3" & Station != "4"), aes(RetDate, Temperature, fill = Station), size = 3.25, shape = 21) +
    labs(title = "Caloosahatchee-East") +
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("Temperature (\u00B0C)", expand = c(0,0), limits = c(0, 40)) +
    BaseForm + FacetForm + West_legend + Station_color_W + Station_fill_W + PlotTitle ,
  NULL,
  #CRW plot
  ggplot() +
    geom_line(data = Tem_CRE_2 %>% filter(Station != "1" & Station != "2"), aes(RetDate, Temperature, color = Station), linewidth = 0.7) +
    geom_point(data = Tem_CRE_2 %>% filter(Station != "1" & Station != "2"), aes(RetDate, Temperature, fill = Station), size = 3.25, shape = 21) +
    labs(title = "Caloosahatchee-West") +     
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("Temperature (\u00B0C)", expand = c(0,0), limits = c(0, 40)) +
    BaseForm + FacetForm + West_legend + Station_color_W + Station_fill_W + PlotTitle ,
  nrow = 3, heights = c(1, -0.05, 1))
#
#
```

```{r SLC DO Figure, fig.cap = "**Figure 8.**  Monthly dissolved oxygen concentration recorded in 2024 at stations in the St. Lucie-North (top), St. Lucie-South (middle), and St. Lucie-Central (bottom) study sites.", fig.height = 10, fig.width = 8, fig.fullwidth=TRUE}
#
ggarrange(
  #SLN plot
  ggplot() +
    geom_line(data = DO_SLC_2 %>% filter(Site == "SLN"), aes(RetDate, DO, color = Station), linewidth = 0.7)+
    geom_point(data = DO_SLC_2 %>% filter(Site == "SLN"), aes(RetDate, DO, fill = Station), size = 3.25, shape = 21) +
    labs(title = "St. Lucie-North") +
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("DO (mg/L)", expand = c(0,0), limits = c(0, 12)) +
    BaseForm + FacetForm + West_legend + Station_color_E + Station_fill_E + PlotTitle,
  NULL,
  #SLS plot
  ggplot() +
    geom_line(data = DO_SLC_2 %>% filter(Site == "SLS"), aes(RetDate, DO, color = Station), linewidth = 0.7)+
    geom_point(data = DO_SLC_2 %>% filter(Site == "SLS"), aes(RetDate, DO, fill = Station), size = 3.25, shape = 21) +
    labs(title = "St. Lucie-South") +     
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("DO (mg/L)", expand = c(0,0), limits = c(0, 12)) +
    BaseForm + FacetForm + Station_color_E + Station_fill_E + PlotTitle + theme(legend.position = "none"),
  NULL,
  #SLC plot
  ggplot() +
    geom_line(data = DO_SLC_2 %>% filter(Site == "SLC"), aes(RetDate, DO, color = Station), linewidth = 0.7)+
    geom_point(data = DO_SLC_2 %>% filter(Site == "SLC"), aes(RetDate, DO, fill = Station), size = 3.25, shape = 21) +
    labs(title = "St. Lucie-Central") +     
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("DO (mg/L)", expand = c(0,0), limits = c(0, 12)) +
    BaseForm + FacetForm + Station_color_E + Station_fill_E + PlotTitle  + theme(legend.position = "none"),
  nrow = 5, heights = c(1, -0.05, 1, -0.05, 1))
#
#
```

```{r LRE DO Figure, fig.cap = "**Figure 9.**  Monthly dissoolved oxygen concentration recorded in 2024 at stations in the Loxahatchee-North (top) and Loxahatchee-South (bottom) study sites.", fig.height = 7, fig.width = 8, fig.fullwidth=TRUE}
#
ggarrange(
  #LXN plot
  ggplot() +
   geom_line(data = DO_LRE_2 %>% filter(Site == "LXN"), aes(RetDate, DO, color = Station), linewidth = 0.7) +
    geom_point(data = DO_LRE_2 %>% filter(Site == "LXN"), aes(RetDate, DO, fill = Station), size = 3.25, shape = 21) +
    labs(title = "Loxahatchee-North") +
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("DO (mg/L)", expand = c(0,0), limits = c(0, 12)) +
    BaseForm + FacetForm + West_legend + Station_color_E + Station_fill_E + PlotTitle,
  NULL,
  #LXS plot
  ggplot() +
    geom_line(data = DO_LRE_2 %>% filter(Site == "LXS"), aes(RetDate, DO, color = Station), linewidth = 0.7) +
    geom_point(data = DO_LRE_2 %>% filter(Site == "LXS"), aes(RetDate, DO, fill = Station), size = 3.25, shape = 21) +
    labs(title = "Loxahatchee-South") +     
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("DO (mg/L)", expand = c(0,0), limits = c(0, 12)) +
    BaseForm + FacetForm + Station_color_E + Station_fill_E + PlotTitle + theme(legend.position = "none"),
  nrow = 3, heights = c(1, -0.05, 1))
#
#
```

```{r CRE DO Figure, fig.cap = "**Figure 10.**  Monthly dissolved oxygen concentration recorded in 2024 at stations in the Caloosahatchee-East (top) and Caloosahatchee-West (bottom) study sites.", fig.height = 7, fig.width = 8, fig.fullwidth=TRUE}
#
ggarrange(
  #CRE plot
  ggplot() +
   geom_line(data = DO_CRE_2 %>% filter(Station != "3" & Station != "4"), aes(RetDate, DO, color = Station), linewidth = 0.7) +
    geom_point(data = DO_CRE_2 %>% filter(Station != "3" & Station != "4"), aes(RetDate, DO, fill = Station), size = 3.25, shape = 21) +
    labs(title = "Caloosahatchee-East") +
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("DO (mg/L)", expand = c(0,0), limits = c(0, 12)) +
    BaseForm + FacetForm + West_legend + Station_color_W + Station_fill_W + PlotTitle ,
  NULL,
  #CRW plot
  ggplot() +
    geom_line(data = DO_CRE_2 %>% filter(Station != "1" & Station != "2"), aes(RetDate, DO, color = Station), linewidth = 0.7) +
    geom_point(data = DO_CRE_2 %>% filter(Station != "1" & Station != "2"), aes(RetDate, DO, fill = Station), size = 3.25, shape = 21) +
    labs(title = "Caloosahatchee-West") +     
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("DO (mg/L)", expand = c(0,0), limits = c(0, 12)) +
    BaseForm + FacetForm + West_legend + Station_color_W + Station_fill_W + PlotTitle ,
  nrow = 3, heights = c(1, -0.05, 1))
#
#
```

```{r SLC pH Figure, fig.cap = "**Figure 11.**  Monthly pH recorded in 2024 at stations in the St. Lucie-North (top), St. Lucie-South (middle), and St. Lucie-Central (bottom) study sites.", fig.height = 10, fig.width = 8, fig.fullwidth=TRUE}
#
ggarrange(
  #SLN plot
  ggplot() +
    geom_line(data = pH_SLC_2 %>% filter(Site == "SLN"), aes(RetDate, pH, color = Station), linewidth = 0.7)+
    geom_point(data = pH_SLC_2 %>% filter(Site == "SLN"), aes(RetDate, pH, fill = Station), size = 3.25, shape = 21) +
    labs(title = "St. Lucie-North") +
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("pH", expand = c(0,0), limits = c(7, 9)) +
    BaseForm + FacetForm + West_legend + Station_color_E + Station_fill_E + PlotTitle,
  NULL,
  #SLS plot
  ggplot() +
    geom_line(data = pH_SLC_2 %>% filter(Site == "SLS"), aes(RetDate, pH, color = Station), linewidth = 0.7)+
    geom_point(data = pH_SLC_2 %>% filter(Site == "SLS"), aes(RetDate, pH, fill = Station), size = 3.25, shape = 21) +
    labs(title = "St. Lucie-South") +     
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("pH", expand = c(0,0), limits = c(7, 9)) +
    BaseForm + FacetForm + Station_color_E + Station_fill_E + PlotTitle + theme(legend.position = "none"),
  NULL,
  #SLC plot
  ggplot() +
    geom_line(data = pH_SLC_2 %>% filter(Site == "SLC"), aes(RetDate, pH, color = Station), linewidth = 0.7)+
    geom_point(data = pH_SLC_2 %>% filter(Site == "SLC"), aes(RetDate, pH, fill = Station), size = 3.25, shape = 21) +
    labs(title = "St. Lucie-Central") +     
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("pH", expand = c(0,0), limits = c(7, 9)) +
    BaseForm + FacetForm + Station_color_E + Station_fill_E + PlotTitle  + theme(legend.position = "none"),
  nrow = 5, heights = c(1, -0.05, 1, -0.05, 1))
#
#
```

```{r LRE pH Figure, fig.cap = "**Figure 12.**  Monthly pH recorded in 2024 at stations in the Loxahatchee-North (top) and Loxahatchee-South (bottom) study sites.", fig.height = 7, fig.width = 8, fig.fullwidth=TRUE}
#
ggarrange(
  #LXN plot
  ggplot() +
   geom_line(data = pH_LRE_2 %>% filter(Site == "LXN"), aes(RetDate, pH, color = Station), linewidth = 0.7) +
    geom_point(data = pH_LRE_2 %>% filter(Site == "LXN"), aes(RetDate, pH, fill = Station), size = 3.25, shape = 21) +
    labs(title = "Loxahatchee-North") +
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("pH", expand = c(0,0), limits = c(7, 9)) +
    BaseForm + FacetForm + West_legend + Station_color_E + Station_fill_E + PlotTitle,
  NULL,
  #LXS plot
  ggplot() +
    geom_line(data = pH_LRE_2 %>% filter(Site == "LXS"), aes(RetDate, pH, color = Station), linewidth = 0.7) +
    geom_point(data = pH_LRE_2 %>% filter(Site == "LXS"), aes(RetDate, pH, fill = Station), size = 3.25, shape = 21) +
    labs(title = "Loxahatchee-South") +     
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("pH", expand = c(0,0), limits = c(7, 9)) +
    BaseForm + FacetForm + Station_color_E + Station_fill_E + PlotTitle + theme(legend.position = "none"),
  nrow = 3, heights = c(1, -0.05, 1))
#
#
```

```{r CRE pH Figure, fig.cap = "**Figure 13.**  Monthly pH recorded in 2024 at stations in the Caloosahatchee-East (top) and Caloosahatchee-West (bottom) study sites.", fig.height = 7, fig.width = 8, fig.fullwidth=TRUE}
#
ggarrange(
  #CRE plot
  ggplot() +
   geom_line(data = pH_CRE_2 %>% filter(Station != "3" & Station != "4"), aes(RetDate, pH, color = Station), linewidth = 0.7) +
    geom_point(data = pH_CRE_2 %>% filter(Station != "3" & Station != "4"), aes(RetDate, pH, fill = Station), size = 3.25, shape = 21) +
    labs(title = "Caloosahatchee-East") +
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("pH", expand = c(0,0), limits = c(7, 9)) +
    BaseForm + FacetForm + West_legend + Station_color_W + Station_fill_W + PlotTitle ,
  NULL,
  #CRW plot
  ggplot() +
    geom_line(data = pH_CRE_2 %>% filter(Station != "1" & Station != "2"), aes(RetDate, pH, color = Station), linewidth = 0.7) +
    geom_point(data = pH_CRE_2 %>% filter(Station != "1" & Station != "2"), aes(RetDate, pH, fill = Station), size = 3.25, shape = 21) +
    labs(title = "Caloosahatchee-West") +     
    scale_x_date("", expand= c(0,0), date_breaks = "1 month", date_labels = "%b", limits = c(End_date %m-% months(12) %m-% days(5), End_date %m-% days(5)))+
    scale_y_continuous("pH", expand = c(0,0), limits = c(7, 9)) +
    BaseForm + FacetForm + West_legend + Station_color_W + Station_fill_W + PlotTitle ,
  nrow = 3, heights = c(1, -0.05, 1))
#
#
```