---
title: "Summary_Data_Output"
author: "ELevine"
date: "2024-06-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

Author <- c("E Levine") #Change to your name
Database <- "Oysters_24-07-01"  #Set the local database to use
Server = "localhost\\ERICALOCALSQL" #Set the local Server to use

Start_date <- as.Date("2022-01-01")
End_date <- as.Date("2022-06-30")

#Packages
if (!require("pacman")) {install.packages("pacman")}
pacman::p_load(odbc, DBI, dbplyr,
  tidyverse, dplyr,  stringr, #DF manipulation
  DT,          #Excel
  lubridate, zoo,         #Dates
  knitr, 
  install = TRUE)

Estuaries <- c("SL", "LX", "CR", "LW")
Sites <- c("CR-E", "CR-W", "LW-L", "LW-R", "LX-N", "LX-S", "SL-C", "SL-N", "SL-S")
CR_order <- c("0230", "0231", "0232", "0233",  #CR
              "0235", "0236", "0237", "0240", "0241", "0312", #LW
              "0242", "0243", "0244", "0246", "0247", "0249", #LX
              "0255", "0256", "0257", "0261", "0262", "0264", "0269", "0270", "0271") #SL
Station_order <- c("CR-E1", "CR-E2", "CR-W3", "CR-W4", #CR
                   "LW-L1", "LW-L2", "LWL-3", "LW-R2", "LW-R3", "LW-R4", #LW
                   "LX-N1", "LX-N2", "LX-N3", "LXS-1", "LX-N2", "LX-S3", #LX
                   "SL-C1", "SL-C2", "SL-C3", "SL-N1", "SL-N2", "SL-N3", "SL-S1", "SL-S2", "SL-S3") #SL

```


```{r DatabaseDownload}
# Connect to Local database server and pull all necessary data, then close connection 
con <- dbConnect(odbc(),
                    Driver = "SQL Server", 
                    Server = Server,
                    Database = Database,
                    Authentication = "ActiveDirectoryIntegrated")

dboFixedLocations <- tbl(con,in_schema("dbo", "FixedLocations")) %>%
  collect() %>% 
  filter(Estuary %in% Estuaries & grepl("^0", FixedLocationID)) %>% #Limit to primary stations, remove "ARRA" and SLN4
  filter(!grepl("^ARRA", StationName) & StationName != "SL-N-4")
hsdbSampleEventWQ <- tbl(con,in_schema("hsdb", "SampleEventWQ")) %>%
  collect() %>% mutate(FixedLocationID = substring(SampleEventID, 19, 22)) %>% #Create FixedLocationID column and filter to matching IDs
  filter(FixedLocationID %in% dboFixedLocations$FixedLocationID & str_detect(SampleEventWQID, 'RCRT')) #Limit to COLL (dermo) data (Pre-2023, WQ is with RCRT. 2023+ is with COLL)
dboSampleEventWQ <- tbl(con,in_schema("dbo", "SampleEventWQ")) %>%
  collect() %>% mutate(FixedLocationID = substring(SampleEventID, 19, 22)) %>% #Create FixedLocationID column and filter to matching IDs
  filter(FixedLocationID %in% dboFixedLocations$FixedLocationID & str_detect(SampleEventWQID, 'COLL')) #Limit to COLL (dermo) data

DBI::dbDisconnect(con)
```

```{r WQ data tables}

#List of WQ params
WQ_params <- c("DO","Pct", "pH", "Sal", "SP", "Temp")

#Combined table of all parameters
WQ_combined <- left_join(rbind((hsdbSampleEventWQ %>% filter(DataStatus == "Proofed")), (dboSampleEventWQ %>% filter(DataStatus == "Proofed"))) %>%
  #Create date columns and Secchi penetration
  mutate(RetDate = as.Date(substring(SampleEventID, 8, 15), format = "%Y%m%d"),
         AnalysisDate = as.Date(floor_date(RetDate, unit = "month")),
         SP = round((Secchi/Depth) * 100, 2)) %>%
  #Filter data to desired date range and select columns needed for summary
  filter(RetDate > Start_date & RetDate < End_date) %>%
  dplyr::select(AnalysisDate, RetDate, SampleEventWQID, SampleEventID, FixedLocationID, DissolvedOxygen, PercentDissolvedOxygen, pH, Salinity, SP, Temperature) %>% rename(DO = DissolvedOxygen, Pct = PercentDissolvedOxygen, Sal = Salinity, Temp = Temperature) %>%
  #Arrange by station then date
  arrange(match(FixedLocationID, c(CR_order)), AnalysisDate),
  #Add simplified StationName 
  dboFixedLocations %>% 
    mutate(StationName = paste0(Estuary, "-", SectionName, StationNumber),
           Site = paste0(Estuary, "-", SectionName)) %>%
    dplyr::select(FixedLocationID, Site, StationName))

##Summary by Station
#Create empty data frame with analysis dates
Station_summary <- data.frame(AnalysisDate = unique(WQ_combined$AnalysisDate))#WQ_combined %>% distinct(Site, RetDate))
for(i in WQ_params){
  for(j in Station_order){
    Summary_jS <- WQ_combined %>% 
      #Select columns for each WQ param, filter to Station by FixedLocationID, and group for summary
      dplyr::select(StationName, AnalysisDate, RetDate, i) %>% filter(StationName == j) %>% group_by(AnalysisDate, RetDate) %>% dplyr::select(-StationName) %>%
      #Rename columns: Add StationName to beginning, reformat RetDate for cleaning
      rename_with(.fn = ~ifelse(.x != "AnalysisDate", paste0(j, "_", .x), .x), .cols = -all_of("AnalysisDate")) %>% rename_with(.fn = ~ifelse(str_detect(.x, "RetDate"), paste0(j,"_", i, "_RetDate"), .x), .cols = everything())
    #
    #Join with existing data
    Station_summary <- left_join(Station_summary, Summary_jS, by = "AnalysisDate")
  }
}


##Summary by Site
#Create empty data frame with analysis dates
Site_summary <- data.frame(AnalysisDate = unique(WQ_combined$AnalysisDate))#WQ_combined %>% distinct(Site, RetDate))
for(i in WQ_params){
  for(j in Sites){
    Summary_j <- WQ_combined %>% 
      #Select columns for each WQ param, filter to Site, and group for summary
      dplyr::select(Site, AnalysisDate, RetDate, i) %>% filter(Site == j) %>% group_by(AnalysisDate, RetDate) %>% 
      #Calculate mean, SD, min, and max of parameter
      summarise(across(.cols = where(is.numeric), .fns = list(A_Mean = mean, B_SD = sd, C_Min = min, D_Max = max), na.rm = T, .names = "{fn}{col}")) %>% 
      #Rename columns: Add Site to beginning, reformat RetDate for cleaning
      rename_with(.fn = ~ifelse(.x != "AnalysisDate", paste0(j, "_", .x), .x), .cols = -all_of("AnalysisDate")) %>% rename_with(.fn = ~ifelse(str_detect(.x, "RetDate"), paste0(j,"_A_", i, "_RetDate"), .x), .cols = everything())
    #
    #Join with existing data
    Site_summary <- left_join(Site_summary, Summary_j, by = "AnalysisDate")
  }
}
#Clean columns for selection and output
Site_summary <- Site_summary %>% rename_with(., function(x){str_replace(x, "(\\_)[A-Z]","")}) 

Site_summary %>% dplyr::select(contains("DO")) #Site DO
Site_summary %>% dplyr::select(contains("Pct")) #Site PctDO
Site_summary %>% dplyr::select(contains("pH")) #Site pH
Site_summary %>% dplyr::select(contains("Sal")) #Site salinity
Site_summary %>% dplyr::select(contains("Temp")) #Site temperature
Site_summary %>% dplyr::select(contains("SP")) #Site Secchi

```
