---
title: "CERP Monthly Report - `r params$Year`-`r params$Month`"
output: word_document
params: 
  Month: "09"  #Enter 2-digit month
  Year: "2023" #Enter 4-digit year
---

```{r VariableSet, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

Author <- c("E Levine") #Change to your name
Database <- "OystersEL_240104"  #Set the local database to use
Server = "localhost\\ERICALOCALSQL" #Set the local Server to use


#Don't modify code in rest of section
Estuaries <- c("SL", "CR")
LocationIDs <- c("0255", "0256", "0257", "0231", "0232")
Month <- params$Month 
Year <- params$Year   
Survey <- ifelse(as.numeric(Month) > 11 | as.numeric(Month) < 3, paste0("Winter", Year),
                 ifelse(as.numeric(Month) > 2 & as.numeric(Month) < 6, paste0("Spring", Year),
                        ifelse(as.numeric(Month) > 5 & as.numeric(Month) < 9, paste0("Summer", Year), paste0("Fall", Year))))
```

```{r PackageLoad & VarSet, echo = FALSE, warning = FALSE, message = FALSE}
# Load necessary R packages
if (!require("pacman")) {install.packages("pacman")}
pacman::p_load(odbc, DBI, dbplyr,
  tidyverse, dplyr,  #DF manipulation
  #readxl,          #Excel
  lubridate,         #Dates
  knitr, here,
  flextable,
  install = TRUE)

MonYr <- paste(month.abb[as.numeric(Month)], Year, sep = " ")
ReportStart <- as.Date(paste(Year, Month, "01", sep = "-")) - months(1)
ReportEnd <- format(ceiling_date(ReportStart %m+% months(2)) - days(1), "%Y-%m-%d")
```

```{r DatabaseDownload}
# Connect to Local database server and pull all necessary data, then close connection 
con <- dbConnect(odbc(),
                    Driver = "SQL Server", 
                    Server = Server,
                    Database = Database,
                    Authentication = "ActiveDirectoryIntegrated")

dboFixedLocations <- tbl(con,in_schema("dbo", "FixedLocations")) %>%
  collect() %>% 
  filter(Estuary %in% Estuaries)
hsdbSampleEventWQ <- tbl(con,in_schema("hsdb", "SampleEventWQ")) %>%
  collect() %>%
  filter(substring(SampleEventID, 1, 2) %in% Estuaries)
dboSampleEventWQ <- tbl(con,in_schema("dbo", "SampleEventWQ")) %>%
  collect() %>%
  filter(substring(SampleEventID, 1, 2) %in% Estuaries)
hsdbRecruitment <- tbl(con,in_schema("hsdb", "Recruitment")) %>%
  collect() %>%
  filter(substring(SampleEventID, 1, 2) %in% Estuaries)
dboRecruitment <- tbl(con,in_schema("dbo", "Recruitment")) %>%
  collect() %>%
  filter(substring(SampleEventID, 1, 2) %in% Estuaries)
hsdbDermo <- tbl(con,in_schema("hsdb", "Dermo")) %>%
  collect() %>%
  filter(substring(SampleEventID, 1, 2) %in% Estuaries)
dboDermo <- tbl(con,in_schema("dbo", "Dermo")) %>%
  collect() %>%
  filter(substring(SampleEventID, 1, 2) %in% Estuaries) %>%
  mutate(DermoMantle = as.numeric(DermoMantle),
         DermoGill = as.numeric(DermoGill))
if(Month == "03" | Month == "06" | Month == "09" | Month == "12"){
  hsdbSurvey <- tbl(con,in_schema("hsdb", "SurveyQuadrat")) %>%
    collect() %>%
    filter(substring(SampleEventID, 1, 2) %in% Estuaries)
  dboSurvey <- tbl(con,in_schema("dbo", "SurveyQuadrat")) %>%
    collect() %>%
    filter(substring(SampleEventID, 1, 2) %in% Estuaries)} else {Survey <- "Survey was not conducted"}
DBI::dbDisconnect(con)
```

```{r DataFilters and Summaries}
# Filter data frames so that only data collected for inclusion in the CERP Monthly Report are present.
FixedLocations1 <- dboFixedLocations %>% 
  mutate(StationNumber = as.numeric(StationNumber)) %>% 
  filter(FixedLocationID %in% LocationIDs) %>% #Only need SLC stations (0255-0257), CR2 (0231), and CR3 (0232)
  select(FixedLocationID,
         Estuary,
         SectionName, 
         StationNumber) %>% 
  distinct()  

### WATER QUALITY ###
WQ1 <- union(hsdbSampleEventWQ, dboSampleEventWQ) %>% 
  mutate(RetDate = as.Date(substring(SampleEventID, 8, 15), format = "%Y%m%d"), 
         FixedLocationID = substring(SampleEventID, 19, 22), 
         AnalysisDate = as.Date(floor_date(RetDate, unit = "month")),
         Plot_Date = as.Date(AnalysisDate + 14),
         SecchiPercent = (Secchi / Depth) * 100) %>%
  select(SampleEventWQID,
         FixedLocationID,
         SampleEventID,
         RetDate,
         AnalysisDate,
         Plot_Date,
         Temperature,
         Salinity,
         DissolvedOxygen,
         pH,
         SecchiPercent) %>% 
  drop_na(Temperature) %>%
  filter(RetDate >= ReportStart & RetDate < ReportEnd & FixedLocationID %in% LocationIDs) %>%
  left_join(FixedLocations1, by = c("FixedLocationID")) 

SLC_WQStats <- WQ1 %>% 
  filter(str_detect(SampleEventWQID, 'COLL') & Estuary == "SL") %>%
  group_by(AnalysisDate, 
           Plot_Date, 
           Estuary,  
           SectionName) %>% 
  summarise(SalMean = mean(Salinity, na.rm = TRUE),
            SalSD = sd(Salinity, na.rm = T))

SLC1_WQStats <- WQ1 %>% 
  filter(str_detect(SampleEventWQID, 'COLL') & Estuary == "SL" & StationNumber == 1) %>%
  group_by(AnalysisDate, 
           Plot_Date, 
           Estuary,  
           SectionName) %>% 
  summarise(SalMean = mean(Salinity, na.rm = TRUE),
            SalSD = sd(Salinity, na.rm = T))

CR_WQStats <- WQ1 %>% 
  filter(str_detect(SampleEventWQID, 'COLL') & Estuary == "CR") %>%
  group_by(AnalysisDate, 
           Plot_Date, 
           Estuary, 
           StationNumber, 
           SectionName) %>% 
  summarise(SalMean = mean(Salinity, na.rm = TRUE),
            SalSD = sd(Salinity, na.rm = T))


### RECRITMENT ###
#SL and CR RCRT calculate differently so compiling separately
SL_Recruit <- union(hsdbRecruitment, dboRecruitment) %>% 
  filter(ShellPosition %in% c(2,3,4,5,8,9,10,11)) %>%
  mutate(DeployedDate = as.Date(DeployedDate), 
         RetDate = as.Date(substring(SampleEventID, 8, 15), format = "%Y%m%d"), 
         FixedLocationID = substring(ShellID, 19, 22), 
         NumDays = as.numeric(RetDate-DeployedDate),
         BottomMonth= NumBottom/(NumDays/28),
         AnalysisDate = as.Date(floor_date(RetDate, unit = "month")),
         Plot_Date = as.Date(AnalysisDate + 14)) %>%
  select(ShellID,
         FixedLocationID,
         SampleEventID,
         DeployedDate,
         RetDate,
         AnalysisDate,
         Plot_Date,
         NumDays,
         ShellPosition,
         NumBottom,
         BottomMonth) %>% 
  filter(RetDate >= ReportStart & RetDate < ReportEnd) %>%
  left_join(FixedLocations1, by = c("FixedLocationID"))

CR_Recruit <- union(hsdbRecruitment, dboRecruitment) %>% 
  filter(ShellPosition %in% c(2,3,4,5,6,7,8,9,10,11)) %>%
  mutate(DeployedDate = as.Date(DeployedDate), 
         RetDate = as.Date(substring(SampleEventID, 8, 15), format = "%Y%m%d"), 
         FixedLocationID = substring(ShellID, 19, 22), 
         NumDays = as.numeric(RetDate-DeployedDate),
         BottomMonth= NumBottom/(NumDays/28),
         AnalysisDate = as.Date(floor_date(RetDate, unit = "month")),
         Plot_Date = as.Date(AnalysisDate + 14)) %>%
  select(ShellID,
         FixedLocationID,
         SampleEventID,
         DeployedDate,
         RetDate,
         AnalysisDate,
         Plot_Date,
         NumDays,
         ShellPosition,
         NumBottom,
         BottomMonth) %>% 
  filter(RetDate >= ReportStart & RetDate < ReportEnd) %>%
  left_join(FixedLocations1, by = c("FixedLocationID"))
  
SLC_RecruitStats <- SL_Recruit %>% 
  filter(Estuary == "SL" & SectionName == "C") %>%
  group_by(AnalysisDate, Plot_Date, Estuary, SectionName) %>% 
  summarise(RcrtMean = mean(BottomMonth, na.rm = TRUE), 
            RcrtSD= sd(BottomMonth, na.rm = TRUE))

SLC1_RecruitStats <- SL_Recruit %>% 
  filter(Estuary == "SL" & SectionName == "C" & StationNumber == 1) %>%
  group_by(AnalysisDate, Plot_Date, Estuary, SectionName, StationNumber) %>% 
  summarise(RcrtMean = mean(BottomMonth, na.rm = TRUE), 
            RcrtSD= sd(BottomMonth, na.rm = TRUE))

CR_RecruitStats <- CR_Recruit %>% 
  filter(Estuary == "CR" & FixedLocationID %in% LocationIDs) %>%
  group_by(AnalysisDate, Plot_Date, Estuary, SectionName, StationNumber) %>% 
  summarise(RcrtMean = mean(BottomMonth, na.rm = TRUE), 
            RcrtSD= sd(BottomMonth, na.rm = TRUE))



### DERMO ###
Dermo1 <- union((hsdbDermo %>% dplyr::select(-OldSampleNumber)), dboDermo) %>% 
  mutate(FixedLocationID = substring(SampleEventID, 19, 22), 
         RetDate = as.Date(substring(SampleEventID, 8, 15), format = "%Y%m%d"),
         AnalysisDate = as.Date(floor_date(RetDate, unit = "month")),
         Plot_Date = as.Date(AnalysisDate + 14),
         DermoSum = as.numeric(ifelse(rowSums(select(., contains("Dermo"))) >0, 1, 0))) %>%
  select(OysterID,
         FixedLocationID,
         SampleEventID,
         RetDate,
         AnalysisDate,
         Plot_Date,
         DermoMantle,
         DermoGill,
         DermoSum) %>% 
  filter(RetDate >= ReportStart & RetDate < ReportEnd & FixedLocationID %in% LocationIDs) %>%
  left_join(FixedLocations1, by = c("FixedLocationID"))

SLC_DermoStats <- Dermo1 %>%
  filter(Estuary == "SL") %>%
  group_by(AnalysisDate, 
           Plot_Date, 
           Estuary,  
           SectionName) %>% 
  summarise(DermoPct = (sum(DermoSum, na.rm = TRUE)/n())*100)

SLC1_DermoStats <- Dermo1 %>%
  filter(Estuary == "SL" & StationNumber == 1) %>%
  group_by(AnalysisDate, 
           Plot_Date, 
           Estuary,  
           SectionName) %>% 
  summarise(DermoPct = (sum(DermoSum, na.rm = TRUE)/n())*100)

CR_DermoStats <- Dermo1 %>%
  filter(Estuary == "CR") %>%
  group_by(AnalysisDate, 
           Plot_Date, 
           Estuary,  
           SectionName,
           StationNumber) %>% 
  summarise(DermoPct = (sum(DermoSum, na.rm = TRUE)/n())*100)

### SURVEY ###
Survey1 <- union(hsdbSurvey, dboSurvey) %>% 
  mutate(FixedLocationID = substring(SampleEventID, 19, 22), 
         RetDate = as.Date(substring(SampleEventID, 8, 15), format = "%Y%m%d"),
         AnalysisDate = as.Date(floor_date(RetDate, unit = "month")),
         Plot_Date = as.Date(AnalysisDate + 14),
         Live = NumLive * 4,
         Dead = NumDead * 4) %>%
  select(QuadratID,
         FixedLocationID,
         SampleEventID,
         RetDate,
         AnalysisDate,
         Plot_Date,
         QuadratNumber,
         Live,
         Dead) %>% 
  filter(RetDate >= ReportStart & RetDate < ReportEnd & FixedLocationID %in% LocationIDs) %>%
  left_join(FixedLocations1, by = c("FixedLocationID"))

SLC_SurveyStats <- Survey1 %>%
  filter(Estuary == "SL") %>%
  group_by(AnalysisDate, 
           Plot_Date, 
           Estuary,  
           SectionName) %>%
  summarise(LiveMean = mean(Live, na.rm = T),
            LiveSD = sd(Live, na.rm = T),
            DeadMean = mean(Dead, na.rm = T),
            DeadSD = sd(Dead, na.rm = T))

SLC1_SurveyStats <- Survey1 %>%
  filter(Estuary == "SL" & StationNumber == 1) %>%
  group_by(AnalysisDate, 
           Plot_Date, 
           Estuary,  
           SectionName, 
           StationNumber) %>%
  summarise(LiveMean = mean(Live, na.rm = T),
            LiveSD = sd(Live, na.rm = T),
            DeadMean = mean(Dead, na.rm = T),
            DeadSD = sd(Dead, na.rm = T))

CR_SurveyStats <- Survey1 %>%
  filter(Estuary == "CR") %>%
  group_by(AnalysisDate, 
           Plot_Date, 
           Estuary,  
           SectionName,
           StationNumber) %>%
  summarise(LiveMean = mean(Live, na.rm = T),
            LiveSD = sd(Live, na.rm = T),
            DeadMean = mean(Dead, na.rm = T),
            DeadSD = sd(Dead, na.rm = T))

```

```{r Data summary tables}
#Output datatables for SLC, SLC1, CRE, CRW
SLC_Summary <- SLC_WQStats %>% dplyr::select(AnalysisDate, SalMean, SalSD)
SLC_RecruitStats %>% dplyr::select(AnalysisDate, RcrtMean, RcrtSD)
SLC_DermoStats %>% dplyr::select(AnalysisDate, DermoPct)
SLC_SurveyStats %>% ungroup() %>% dplyr::select(AnalysisDate, LiveMean:DeadSD)
```

