---
title: "F5595 Final Figures"
author: "ELevine"
date: "`r Sys.Date()`"
output: 
  word_document: 
    reference_docx: Monthly-Reports-template.docx
    fig_caption: yes
params:
  Start_date: "2023-10-01"
  End_date: "2025-09-30"
  Excel_name: "PBC_5595"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
# make sure to check flow scale ranges when plotting Sal/Flow plots
Estuary_code <- c("LW", "LW-L", "LW-R")
Start_date <- as.Date(params$Start_date)
End_date <- as.Date(params$End_date)

#Packages
if (!require("pacman")) {install.packages("pacman")}
#p_unlock()
pacman::p_load(odbc, DBI, dbplyr,
  tidyverse, dplyr,  stringr, #DF manipulation
  DT, openxlsx,         #Excel
  lubridate, zoo,         #Dates
  knitr, kableExtra, scales, gt, gtExtras, ggpubr, ggpattern, magick, flextable,
  install = TRUE)
```

```{r FigureFormatting, include = FALSE}
#
PBC_sites <- c("LWL", "LWR")
#
#Shared formatting for figure consistency
BaseForm <- theme_classic() +
  theme(panel.border = element_rect(color = "black", fill = NA), #Add border
        axis.title = element_text(family = "serif", color = "black", size = 17), axis.title.x = element_text(margin = margin(t = 12)), #Adjust axis title and text
        axis.text = element_text(family = "serif", color = "black", size = 12), 
        axis.line = element_line(color = "black"),
        axis.ticks.length.x = unit(0.10, "cm"),
        axis.ticks.length.y = unit(0.15, "cm"))

Survey_legend <- theme(legend.position = "inside", legend.position.inside = c(.25, .97), legend.justification = c("left", "top"), legend.box.just = "left", #legend.box.spacing = unit(0.05, "lines"), #Adjust legend position
                     legend.background = element_rect(color = "black", fill = "white", linetype = "solid"),
                     legend.title = element_blank(), legend.key.spacing.y = unit(0.20, "lines"),
                     legend.key.width = unit(0.0001, "pt"), legend.key.height = unit(0.000001, "pt"), #Adjust legend title and spacing
                     legend.text = element_text(family = "serif", color = "black", size = 12))

Legend <- theme(legend.position = "inside", legend.position.inside = c(.005, .97), legend.justification = c("left", "top"), legend.box.just = "left", legend.box.spacing = unit(0.15, "lines"), #Adjust legend position
                     legend.background = element_rect(color = "black", fill = "white", linetype = "solid"),
                     legend.title = element_blank(), legend.key.height = unit(0.7, "lines"), legend.key.spacing.y = unit(0.25, "lines"),
                     legend.key.width = unit(1.5, "lines"), #Adjust legend title and spacing
                     legend.text = element_text(family = "serif", color = "black", size = 12))

FacetForm <- theme(strip.placement = "outside", strip.text.x.top = element_text(vjust = 1, hjust = 0, size = 13, family = "serif"), strip.clip = "off", panel.spacing.y = unit(0.5, "lines"), strip.background = element_blank())

PlotTitle <- theme(plot.title = element_text(size = 13, family = "serif", margin = margin(b = 0.07, t = 0.025)))

#Color and shape to station number
Stat_pal <- c(rgb(0, 0, 228, maxColorValue = 255), rgb(245, 0, 0, maxColorValue = 255), rgb(0, 118, 0, maxColorValue = 255), rgb(102, 0, 102, maxColorValue = 255))
Stations <- c("1" = "Station 1", "2" = "Station 2", "3" = "Station 3", "4" = "Station 4") 
Station_fill <- scale_fill_manual("", labels = Stations, values = setNames(Stat_pal, 1:4), na.value = "#999999")
Station_color <- scale_color_manual("", labels = Stations, values = setNames(Stat_pal, 1:4), na.value = "#999999")
Station_shape <- scale_shape_manual("",labels = Stations, values = setNames(c(21, 25, 22, 23), 1:4))

#Color to Stage
Stat_pal3 <- c(rgb(255, 255, 255, maxColorValue = 255), rgb(153, 255, 255, maxColorValue = 255), rgb(0, 0, 255, maxColorValue = 255), rgb(0, 0, 102, maxColorValue = 255))
Stages <- c("Ind" = "Indifferent", "Dev" = "Developing", "Rip" = "Ripe/Spawning", "Spe" = "Spent/Recyling") 
Stage_fill <- scale_fill_manual("", labels = Stages, values = Stat_pal3, na.value = "#999999")
#
#Sediment formatting
Sediment_list <- c("Rate", "OrgContent", "OrgWt")
Stat_pal2 <- c(rgb(0, 0, 228, maxColorValue = 255), rgb(245, 0, 0, maxColorValue = 255))
Positions <- c("N" = "North", "S" = "South")
Position_fill <- scale_fill_manual("", labels = Positions, values = Stat_pal2, na.value = "#999999")
Position_color <- scale_color_manual("", labels = Positions, values = Stat_pal2, na.value = "#999999")
#
#
```

```{r Data gather from summary file, include=FALSE}
###Water Quality
WQ_Sal_s <-  readWorkbook("../Data/CERP_PBC_WQ_Summary_Data.xlsx", sheet = 'Salinity Station', detectDates = TRUE, check.names = TRUE)
LW_Flow <- readWorkbook("Data/LWL_WQ_Data.xlsx", sheet = 'Flow_df', detectDates = TRUE, check.names = TRUE) %>% filter(Date >= Start_date %m-% days(15) & Date <= End_date) %>% dplyr::select(Analysis_Date, Estuary, Date, S155_Flow, S41_Flow, S44_Flow, LWSum)
WQ_Tem_s <-  readWorkbook("../Data/CERP_PBC_WQ_Summary_Data.xlsx", sheet = 'Temp Station', detectDates = TRUE, check.names = TRUE)
WQ_pH_s <-  readWorkbook("../Data/CERP_PBC_WQ_Summary_Data.xlsx", sheet = 'pH Station', detectDates = TRUE, check.names = TRUE)
WQ_DO_s <-  readWorkbook("../Data/CERP_PBC_WQ_Summary_Data.xlsx", sheet = 'DO Station', detectDates = TRUE, check.names = TRUE)
WQ_Secchi_s <-  readWorkbook("../Data/CERP_PBC_WQ_Summary_Data.xlsx", sheet = 'Secchi Station', detectDates = TRUE, check.names = TRUE)
#
Counts_df <- readWorkbook("../Data/CERP_PBC_Summary_Data.xlsx", sheet = 'DeadRatio Station', detectDates = TRUE, check.names = TRUE)
SH_df <- readWorkbook("../Data/CERP_PBC_Summary_Data.xlsx", sheet = 'SH Station', detectDates = TRUE, check.names = TRUE)
Rcrt_df <- readWorkbook("../Data/CERP_PBC_Summary_Data.xlsx", sheet = 'Rcrt Station', detectDates = TRUE, check.names = TRUE)
Repro_df <- readWorkbook("../Data/CERP_PBC_Summary_Data.xlsx", sheet = 'Repro', detectDates = TRUE, check.names = TRUE)
Dermo_df <- readWorkbook("../Data/CERP_PBC_Summary_Data.xlsx", sheet = 'Dermo Station', detectDates = TRUE, check.names = TRUE)
Sedi_sta <- readWorkbook("../Data/CERP_PBC_Summary_Data.xlsx", sheet = 'Sedi Stations', detectDates = TRUE, check.names = TRUE)
Sedi_pos <- readWorkbook("../Data/CERP_PBC_Summary_Data.xlsx", sheet = 'Sedi Position', detectDates = TRUE, check.names = TRUE)
#
```

```{r Water Quality Data selection and cleaning}
#
##Salinity
names(WQ_Sal_s) <- gsub("\\.", "", names(WQ_Sal_s))
PBC_Sal <- WQ_Sal_s %>% dplyr::select(contains("LW")) %>% 
  filter(LWL_RetDate_Sal > Start_date & LWL_RetDate_Sal < End_date) %>% 
  rename("RetDate" = LWL_RetDate_Sal) %>% 
  dplyr::select(-LWR_RetDate_Sal) %>% 
  gather(SiteStation, Salinity, -RetDate) %>% 
  mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("LWL", "LWR")), Station = factor(substr(SiteStation, 4, 4)), Helper = case_when(is.na(Salinity) ~ "*", TRUE ~ NA)) %>% 
  #Add legend placeholder for Flow data
  rbind(data.frame(RetDate = NA, SiteStation = 'LWL4_Flow', Salinity = NA, Site = 'LWL', Station = '4', Helper = NA, stringsAsFactors = TRUE)) %>% 
  rbind(data.frame(RetDate = NA, SiteStation = 'LWR1_Flow', Salinity = NA, Site = 'LWL', Station = '1', Helper = NA, stringsAsFactors = TRUE))
#
#
#Flow - Need data for each site for plotting
LW_Flow <- rbind(LW_Flow %>% dplyr::select(Date, LWSum) %>% mutate(Site = "LWL"), 
                    LW_Flow %>% dplyr::select(Date, LWSum) %>% mutate(Site = "LWR")) %>%
  mutate(Rescale = (LWSum - min(LWSum, na.rm = T))/(max(LWSum, na.rm = T) - min(LWSum, na.rm = T))*(40-0)+0) #Rescale flow to salinity axis limits for plotting
#
#
#
##Temperature
names(WQ_Tem_s) <- gsub("\\.", "", names(WQ_Tem_s))
PBC_Temp <- WQ_Tem_s %>% 
  dplyr::select(contains("LW")) %>% 
  filter(LWL_RetDate_Temp > Start_date & LWL_RetDate_Temp < End_date) %>% 
  dplyr::select(-LWR_RetDate_Temp) %>% 
  rename("RetDate" = LWL_RetDate_Temp) %>%
  gather(SiteStation, Temperature, -RetDate) %>% 
  mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("LWL", "LWR")), Station = as.factor(substr(SiteStation, 4, 4)))
#
#
#
##DO
names(WQ_DO_s) <- gsub("\\.", "", names(WQ_DO_s))
PBC_DO <- WQ_DO_s %>% 
  dplyr::select(contains("LW")) %>% 
  filter(LWL_RetDate_DO > Start_date & LWL_RetDate_DO < End_date) %>% 
  dplyr::select(-LWR_RetDate_DO) %>% 
  rename("RetDate" = LWL_RetDate_DO) %>% 
  gather(SiteStation, DO, -RetDate) %>% 
  mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("LWL", "LWR")), Station = as.factor(substr(SiteStation, 4, 4)))
#
#
#
##pH
names(WQ_pH_s) <- gsub("\\.", "", names(WQ_pH_s))
PBC_pH <- WQ_pH_s %>% 
  dplyr::select(contains("LW")) %>% 
  filter(LWL_RetDate_pH > Start_date & LWL_RetDate_pH < End_date) %>% 
  dplyr::select(-LWR_RetDate_pH) %>% 
  rename("RetDate" = LWL_RetDate_pH) %>% 
  gather(SiteStation, pH, -RetDate) %>% 
  mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("LWL", "LWR")), Station = as.factor(substr(SiteStation, 4, 4)))
#
#
#
##Secchi
names(WQ_Secchi_s) <- gsub("\\.", "", names(WQ_Secchi_s))
PBC_SP <- WQ_Secchi_s %>% 
  dplyr::select(contains("LW")) %>% 
  filter(LWL_RetDate_SP > Start_date & LWL_RetDate_SP < End_date) %>% 
  dplyr::select(-LWR_RetDate_SP) %>% 
  rename("RetDate" = LWL_RetDate_SP) %>% 
  gather(SiteStation, SP, -RetDate) %>% 
  mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("LWL", "LWR")), Station = as.factor(substr(SiteStation, 4, 4)))
#
#
#
```

```{r Data selection and cleaning}
#
####SURVEY DATA
names(Counts_df) <- gsub("\\.", "", names(Counts_df))
Surveys <- Counts_df %>% 
  arrange(AnalysisDate) %>% 
  filter(AnalysisDate >= Start_date & AnalysisDate <= End_date) %>% 
  dplyr::select(AnalysisDate, Survey)
Counts <- Counts_df %>% 
  filter(AnalysisDate >= Start_date & AnalysisDate <= End_date) %>% 
  dplyr::select(Survey, AnalysisDate, contains("LW")) %>% 
  gather(SiteStation, DataType, -Survey, -AnalysisDate) %>% 
  mutate(Measure = case_when(grepl("Mean", SiteStation) ~ "Mean", 
                             grepl("SD", SiteStation) ~ "SD", 
                             TRUE ~ NA)) %>%
  mutate(SiteStation = case_when(grepl("Dead", SiteStation) ~ substr(SiteStation, 1, 14), 
                                 grepl("Live", SiteStation) ~ substr(SiteStation, 1, 9), 
                                 TRUE ~ "MISSING INFO")) %>% 
  spread(Measure, DataType) %>% 
  mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("LWL", "LWR")), 
         Station = as.factor(substr(SiteStation, 4, 4)), 
         Helper = case_when(is.na(Mean) ~ "*", 
                            grepl("Winter", Survey) & is.na(Mean) ~ "*", 
                            grepl("Summer", Survey) & is.na(Mean) ~ "*", TRUE ~ NA))
#
#
#
names(SH_df) <- gsub("\\.", "", names(SH_df))
SHs <- SH_df %>% 
  dplyr::select(Survey, AnalysisDate, contains("LW")) %>% 
  filter(AnalysisDate >= End_date %m-% months(13)) %>% 
  gather(SiteStation, Value, -Survey, -AnalysisDate) %>% 
  mutate(Measure = case_when(grepl("Mean", SiteStation) ~ "Mean", 
                             grepl("SD", SiteStation) ~ "SD", 
                             TRUE ~ NA)) %>% 
  mutate(SiteStation = substr(SiteStation, 1, 4)) %>% 
  spread(Measure, Value) %>% 
  mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("LWL", "LWR")), 
         Station = as.factor(substr(SiteStation, 4, 4)), 
         Helper = case_when(is.na(Mean) ~ "*", 
                            grepl("Winter", Survey) & is.na(Mean) ~ "*", 
                            grepl("Summer", Survey) & is.na(Mean) ~ "*", 
                            TRUE ~ NA))
#
#
#
####DERMO DATA
names(Dermo_df) <- gsub("\\.", "", names(Dermo_df))
DermoP <- Dermo_df %>% 
  dplyr::select(contains("LW")) %>% 
  dplyr::select(contains('RetDate')|contains('Pct'))  %>% 
  filter(LWL_RetDate >= Start_date & LWL_RetDate <= End_date) %>% 
  dplyr::select(-LWR_RetDate)  %>% 
  rename("RetDate" = LWL_RetDate) %>% 
  gather(SiteStation, Value, -RetDate) %>% 
  mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("LWL", "LWR")), 
         Station = as.factor(substr(SiteStation, 4, 4)), 
         Helper = case_when(is.na(Value) ~ "*", TRUE ~ NA))
#
#
DermoI <- Dermo_df %>% 
  dplyr::select(contains("LW")) %>% 
  dplyr::select(contains('RetDate')|-contains('Pct')) %>% 
  filter(LWL_RetDate >= Start_date & LWL_RetDate <= End_date) %>% 
  dplyr::select(-LWR_RetDate)  %>% 
  rename("RetDate" = LWL_RetDate)  %>% 
  gather(SiteStation, Value, -RetDate) %>% 
  mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("LWL", "LWR")), 
         Station = as.factor(substr(SiteStation, 4, 4)), 
         Measure = case_when(grepl("Mean", SiteStation) ~ "Mean", 
                             grepl("SD", SiteStation) ~ "SD", 
                             TRUE ~ NA), 
         SiteStation = substr(SiteStation, 1, 4)) %>%  
  spread(Measure, Value) %>% 
  mutate(Helper = case_when(is.na(Mean) ~ "*", TRUE ~ NA))
#
#
#
####REPRO DATA
names(Repro_df) <- gsub("\\.", "", names(Repro_df))
Repro_PBC <- Repro_df %>% 
  dplyr::select(contains("LW")) %>% 
  filter(LWL_RetDate >= Start_date & LWL_RetDate <= End_date) %>% 
  dplyr::select(-LWR_RetDate)  %>% 
  rename("RetDate" = LWL_RetDate) %>% 
  gather(SiteStation, Value, -RetDate) %>% 
  mutate(Stage = factor(substr(SiteStation, 5, 7), levels = c("Ind", "Dev", "Rip", "Spe")), 
         Site = factor(substr(SiteStation, 1, 3), levels = c("LWL", "LWR")), 
         Helper = case_when(is.na(Value) ~ "*", TRUE ~ NA))
#
#
#
####RECRUITMENT DATA
names(Rcrt_df) <- gsub("\\.", "", names(Rcrt_df))
Recruits <- Rcrt_df %>% 
  dplyr::select(contains("LW")) %>% 
  filter(LWL_RetDate >= Start_date & LWL_RetDate <= End_date) %>% 
  dplyr::select(-LWR_RetDate)  %>% 
  rename("RetDate" = LWL_RetDate) %>% 
  gather(SiteStation, Value, -RetDate) %>% 
  mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("LWL", "LWR")), 
         Station = as.factor(substr(SiteStation, 4, 4)), 
         Measure = case_when(grepl("Mean", SiteStation) ~ "Mean", 
                             grepl("SD", SiteStation) ~ "SD", 
                             TRUE ~ NA), 
         SiteStation = substr(SiteStation, 1, 4)) %>%  
  spread(Measure, Value) %>% 
  mutate(Helper = case_when(is.na(Mean) ~ "*", TRUE ~ NA))
#
#
#
####SEDIMENT DATA
names(Sedi_sta) <- gsub("\\.", "", names(Sedi_sta))
names(Sedi_pos) <- gsub("\\.", "", names(Sedi_pos))
Sed_sta_rate <- Sedi_sta %>% 
  dplyr::select(contains("Ret") | contains("Rate")) %>% 
  filter(LWL_RetDate >= Start_date & LWL_RetDate <= End_date) %>% 
  rename("RetDate" = LWL_RetDate) %>% 
  dplyr::select(-LWR_RetDate) %>% 
  gather(SiteStation, Value, -RetDate) %>% 
  mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("LWL", "LWR")), 
         Station = as.factor(substr(SiteStation, 4, 4)), 
         Measure = case_when(grepl("Mean", SiteStation) ~ "Mean", 
                             grepl("SD", SiteStation) ~ "SD", 
                             TRUE ~ NA)) %>% 
  dplyr::select(-SiteStation) %>% 
  spread(Measure, Value) %>% 
  mutate(Helper = case_when(is.na(Mean) ~ "*", 
                            TRUE ~ NA))
Sed_sta_org <- Sedi_sta %>% 
  dplyr::select(contains("Ret") | contains("Pct")) %>% 
  filter(LWL_RetDate >= Start_date & LWL_RetDate <= End_date) %>% 
  rename("RetDate" = LWL_RetDate) %>% 
  dplyr::select(-LWR_RetDate) %>% 
  gather(SiteStation, Value, -RetDate) %>% 
  mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("LWL", "LWR")), 
         Station = as.factor(substr(SiteStation, 4, 4)), 
         Measure = case_when(grepl("Mean", SiteStation) ~ "Mean", 
                             grepl("SD", SiteStation) ~ "SD", 
                             TRUE ~ NA)) %>% 
  dplyr::select(-SiteStation) %>% 
  spread(Measure, Value) %>% 
  mutate(Helper = case_when(is.na(Mean) ~ "*", 
                            TRUE ~ NA))
Sed_sta_wt <- Sedi_sta %>% 
  dplyr::select(contains("Ret") | contains("Wt")) %>% 
  filter(LWL_RetDate >= Start_date & LWL_RetDate <= End_date) %>% 
  rename("RetDate" = LWL_RetDate) %>% 
  dplyr::select(-LWR_RetDate) %>% 
  gather(SiteStation, Value, -RetDate) %>% 
  mutate(Site = factor(substr(SiteStation, 1, 3), levels = c("LWL", "LWR")), 
         Station = as.factor(substr(SiteStation, 4, 4)), 
         Measure = case_when(grepl("Mean", SiteStation) ~ "Mean", 
                             grepl("SD", SiteStation) ~ "SD", 
                             TRUE ~ NA)) %>% 
  dplyr::select(-SiteStation) %>% 
  spread(Measure, Value) %>% 
  mutate(Helper = case_when(is.na(Mean) ~ "*", TRUE ~ NA))
#
Sedi_positions <- Sedi_pos %>% 
  dplyr::select(-AnalysisDate) %>% 
  rename("RetDate" = North_RetDate) %>% 
  filter(RetDate >= Start_date & RetDate <= End_date) %>% 
  gather(Info, Value, -RetDate) %>% 
  mutate(Position = factor(substr(Info, 1, 5)), 
         Measure = case_when(grepl("Mean", Info) ~ "Mean", 
                             grepl("SD", Info) ~ "SD", 
                             TRUE ~ NA), 
         Parameter = case_when(grepl("Rate", Info) ~ "Rate", 
                               grepl("Pct", Info) ~ "OrgContent", 
                               grepl("Wt", Info) ~ "OrgWt", 
                               TRUE ~ NA)) %>% 
  dplyr::select(-Info)  %>% 
  spread(Measure, Value) %>% 
  mutate(Helper = case_when(is.na(Mean) ~ "*", 
                            TRUE ~ NA))
#
#
```