---
output: 
  word_document:
  toc: true
---

```{r VariableSet, echo = FALSE, warning = FALSE, message = FALSE}
# Set your variables
ReportEnd <- as.Date("2024-12-31")  # Report End Date, currently no filter is set to use this. May need to modify somewhere
Database = "OysterLocalMD20241118"  # Set the local database to use
Server = "localhost\\LOCALSQL" # Set the local Server to use
```

```{r PackageLoad, echo = FALSE, warning = FALSE, message = FALSE}
# Load necessary R packages
library(tidyverse)
library(odbc)
library(DBI)
library(dbplyr)
library(lubridate)
library(knitr)
library(ggpubr)
library(patchwork) #Required for arranging multiple plots, more flexible
library(scales)
```

```{r ConfigureChunks, warning=FALSE, include=FALSE}
# Configure chunks
knitr::opts_chunk$set(
	echo = FALSE,
	fig.height = 10,
	fig.width = 8,
	message = FALSE,
	warning = FALSE
)

ReportStart <- floor_date(ReportEnd %m-% months(14), unit = "month") #May need to revise this
QuarterStart <- floor_date(ReportEnd %m-% months(2), unit = "month") #Probably won't need this
Estuaries <- c("AB")
```

```{r Functions}
### Filter Functions ###
FilterFunction1 <- function(data) {
  data %>% 
    mutate(TripDate = as.Date(substring(QuadratID, 8, 15), format = "%Y%m%d"),
         FixedLocationID = substring(QuadratID, 19, 22),
         Year = year(TripDate)) %>%
    left_join(FixedLocations1, by = c("FixedLocationID")) %>%
    mutate(Season = case_when(
          month(ymd(TripDate)) >= 1 & month(ymd(TripDate)) <= 6 ~ "Spring",
          month(ymd(TripDate)) > 6 ~ "Fall",
          TRUE ~ "Invalid")) %>%
    mutate(Season_Year = paste(Season, Year, sep = " ")) %>%
    mutate(TimeSinceCultched = as.numeric(interval(DateLastCultched, TripDate), "years")) %>%
    mutate(ProjectGroup = case_when(
      grepl("RESTORE", StationName) ~ "RESTORE 2017",
      grepl("Baywide", StationName) ~ "Baywide",
      grepl("NFWF", StationName) & Year < 2019 ~ "NFWF 2015",
      grepl("SBM", StationName) & TimeSinceCultched > 0 ~ "NFWF 2021",
      TRUE ~ "Historic Uncultched")) %>%
    mutate(CultchAge = case_when(
      is.na(TimeSinceCultched) ~ "Historic Uncultched",
      TimeSinceCultched < 0 ~ "Historic Uncultched",
      TimeSinceCultched > 0 & TimeSinceCultched < 5 ~ "Recently Cultched",
      TimeSinceCultched >= 5 ~ "Previously Cultched"))
}


```

```{r DatabaseDownload}
# Connect to Local database server and pull all necessary data, then close connection 
con <- dbConnect(odbc(),
                    Driver = "SQL Server", 
                    Server = Server,
                    Database = Database,
                    Authentication = "ActiveDirectoryIntegrated")

dboFixedLocations <- tbl(con,in_schema("dbo", "FixedLocations")) %>%
  collect() %>% 
  filter(Estuary %in% Estuaries)

hsdbSurveyQuadrat <- tbl(con,in_schema("hsdb", "SurveyQuadrat")) %>%
  collect() %>%
  filter(substring(SampleEventID, 1, 2) %in% Estuaries)
  
dboSurveyQuadrat <- tbl(con,in_schema("dbo", "SurveyQuadrat")) %>%
  collect() %>%
  filter(substring(SampleEventID, 1, 2) %in% Estuaries)

hsdbSurveySH <- tbl(con,in_schema("hsdb", "SurveySH")) %>%
  collect() %>%
  mutate(ShellHeight = as.integer(ShellHeight)) %>%
  filter(substring(QuadratID, 1, 2) %in% Estuaries)

dboSurveySH <- tbl(con,in_schema("dbo", "SurveySH")) %>%
  collect()%>%
  mutate(ShellHeight = as.integer(ShellHeight)) %>%
  filter(substring(QuadratID, 1, 2) %in% Estuaries)

hsdbSBMQuadrat <- tbl(con,in_schema("hsdb", "ShellBudgetQuadrat")) %>%
  collect() %>%
  filter(substring(SampleEventID, 1, 2) %in% Estuaries)
  
dboSBMQuadrat <- tbl(con,in_schema("dbo", "ShellBudgetQuadrat")) %>%
  collect() %>%
  filter(substring(SampleEventID, 1, 2) %in% Estuaries)

hsdbSBMSH <- tbl(con,in_schema("hsdb", "ShellBudgetSH")) %>%
  collect() %>%
  filter(substring(QuadratID, 1, 2) %in% Estuaries)

dboSBMSH <- tbl(con,in_schema("dbo", "ShellBudgetSH")) %>%
  collect()%>%
  filter(substring(QuadratID, 1, 2) %in% Estuaries)

DBI::dbDisconnect(con)

```

```{r DataFiltersBasic}
# Filter data frames so that only data collected for inclusion in the DMFM Report are present.
FixedLocations1 <- dboFixedLocations %>% 
  mutate(StationNumber = as.numeric(StationNumber),
         DateLastCultched = as.Date(DateLastCultched)) %>%
  select(FixedLocationID,
         Estuary,
         SectionName,
         StationName,
         ParcelName,
         StationNumber,
         StationNameNumber,
         DateLastCultched) %>% 
  distinct()
 
### QUADRATS ###  
  # Survey QUADRATS #
Survey_Quad1 <- union_all(dboSurveyQuadrat, hsdbSurveyQuadrat) %>%
  select(QuadratID,
         NumLive,
         TotalWeight,
         Comments)

  # SBM QUADRATS # 
SBM_Quad1 <- union_all(dboSBMQuadrat, hsdbSBMQuadrat) %>%
  rename(TotalWeight = TotalSampleWeight, # Must rename the columns so we can union them together
         NumLive = NumLiveOysters) %>%
  select(QuadratID,
         NumLive,
         TotalWeight,
         Comments)

  # ALL Quadrats # 
Quadrats_ALL <- union(Survey_Quad1, SBM_Quad1) %>%
  FilterFunction1() %>%
  select(QuadratID,
         FixedLocationID,
         TripDate,
         Estuary,
         SectionName,
         StationName,
         StationNumber,
         ParcelName,
         StationNameNumber,
         ProjectGroup,
         CultchAge,
         TimeSinceCultched,
         Season,
         Year,
         Season_Year,
         NumLive,
         TotalWeight,
         Comments)

##### 
### SHELL HEIGHTS ###
  # Survey SHELL HEIGHTS #
Survey_SH1 <- union_all(dboSurveySH, hsdbSurveySH) %>%
  select(ShellHeightID, 
         QuadratID, 
         ShellHeight,
         Comments)

  # SBM SHELL HEIGHTS #
SBM_SH1 <- union_all(dboSBMSH, hsdbSBMSH) %>%
  filter(LiveOrDead != "Dead") %>% ### Remove measures of dead
  select(ShellHeightID, 
         QuadratID, 
         ShellHeight,
         Comments)

  # ALL Shell Heights #
ShellHeights_ALL <- union(Survey_SH1, SBM_SH1) %>%
  FilterFunction1() %>%
  select(QuadratID,
         FixedLocationID,
         TripDate,
         Estuary,
         SectionName,
         StationName,
         StationNumber,
         ParcelName,
         StationNameNumber,
         ProjectGroup,
         CultchAge,
         TimeSinceCultched,
         Season,
         Year,
         Season_Year,
         ShellHeight,
         Comments)

```

``` {r RemoveUneededFrames}
### Remove unneeded data frames

rm(dboFixedLocations, dboSBMQuadrat, dboSurveyQuadrat,hsdbSBMQuadrat, hsdbSurveyQuadrat, SBM_Quad1, Survey_Quad1)

rm(FixedLocations1, dboSBMSH, dboSurveySH, hsdbSBMSH, hsdbSurveySH, Survey_SH1, SBM_SH1)

```

``` {r BasicStats}

### Provides how many were measured for each size class for each quadrat
SHMeasures <- ShellHeights_ALL %>%
  group_by(QuadratID) %>%
  summarize(TotalNumMeasured = sum(!is.na(ShellHeight)),
            Count_1_to_15 = sum(ifelse(ShellHeight >= 1 & ShellHeight <= 15, 1, 0), na.rm = TRUE),
            Count_16_to_30 = sum(ifelse(ShellHeight >= 16 & ShellHeight <= 30, 1, 0), na.rm = TRUE),
            Count_31_to_45 = sum(ifelse(ShellHeight >= 31 & ShellHeight <= 45, 1, 0), na.rm = TRUE),
            Count_46_to_60 = sum(ifelse(ShellHeight >= 46 & ShellHeight <= 60, 1, 0), na.rm = TRUE),
            Count_61_to_75 = sum(ifelse(ShellHeight >= 61 & ShellHeight <= 75, 1, 0), na.rm = TRUE),
            Count_76_to_90 = sum(ifelse(ShellHeight >= 76 & ShellHeight <= 90, 1, 0), na.rm = TRUE),
            Count_91_plus = sum(ifelse(ShellHeight >= 91, 1, 0), na.rm = TRUE),
            Count_Spat_1_to_30 = sum(ifelse(ShellHeight >= 1 & ShellHeight <= 30, 1, 0), na.rm = TRUE),
            Count_Seed_31_to_75 = sum(ifelse(ShellHeight >= 31 & ShellHeight <= 75, 1, 0), na.rm = TRUE),
            Count_Legal_76_plus = sum(ifelse(ShellHeight >= 76, 1, 0), na.rm = TRUE)
            )

### Provide stats for how many live oysters there were in each quadrat, by size class
QuadStats1 <- left_join(Quadrats_ALL, SHMeasures, by = c("QuadratID"))

QuadStats2 <- QuadStats1 %>%
  mutate(
    Num_1_to_15 = if_else(TotalNumMeasured == 0, 0, (Count_1_to_15 * NumLive) / TotalNumMeasured),
    Num_16_to_30 = if_else(TotalNumMeasured == 0, 0, (Count_16_to_30 * NumLive) / TotalNumMeasured),
    Num_31_to_45 = if_else(TotalNumMeasured == 0, 0, (Count_31_to_45 * NumLive) / TotalNumMeasured),
    Num_46_to_60 = if_else(TotalNumMeasured == 0, 0, (Count_46_to_60 * NumLive) / TotalNumMeasured),
    Num_61_to_75 = if_else(TotalNumMeasured == 0, 0, (Count_61_to_75 * NumLive) / TotalNumMeasured),
    Num_76_to_90 = if_else(TotalNumMeasured == 0, 0, (Count_76_to_90 * NumLive) / TotalNumMeasured),
    Num_91_plus = if_else(TotalNumMeasured == 0, 0, (Count_91_plus * NumLive) / TotalNumMeasured),
    Num_Spat_1_to_30 = if_else(TotalNumMeasured == 0, 0, (Count_Spat_1_to_30 * NumLive) / TotalNumMeasured),
    Num_Seed_31_to_75 = if_else(TotalNumMeasured == 0, 0, (Count_Seed_31_to_75 * NumLive) / TotalNumMeasured),
    Num_Legal_76_plus = if_else(TotalNumMeasured == 0, 0, (Count_Legal_76_plus * NumLive) / TotalNumMeasured)
  ) %>%
  select(-starts_with("Count_")) # Remove Count columns as they are no longer needed

```

``` {r AllOysterStats}

# Set up

QuadStats_ALL_Oys <- QuadStats2  

summarise_ALL <- function(data) {
  summarised_data <- data %>%
    summarise(NumLiveMean = mean(NumLive, na.rm = TRUE),
            NumLiveSD = sd(NumLive, na.rm = TRUE),
            TotalWeightMean = mean(TotalWeight, na.rm = TRUE),
            TotalWeightSD = sd(TotalWeight, na.rm = TRUE)) %>%
    mutate(OysterDensityMean = NumLiveMean * 4,
           OysterDensitySD = NumLiveSD * 4,
           WeightDensityMean = TotalWeightMean * 4,
           WeightDensitySD = TotalWeightSD * 4)
  return(summarised_data)
}

# Stats for Total Oyster Density and Total Weight Density by Year and ProjectGroup
QuadStats_ALL_Oys1 <- QuadStats_ALL_Oys %>%
  group_by(Year, 
           ProjectGroup) %>%
  summarise_ALL() %>%
  arrange(Year,
          ProjectGroup)

# Stats for Total Oyster Density and Total Weight Density by Year and Section and ProjectGroup
QuadStats_ALL_Oys2 <- QuadStats_ALL_Oys %>%
  group_by(Year, 
           ProjectGroup,
           SectionName) %>%
  summarise_ALL() %>%
  arrange(Year, 
          SectionName, 
          ProjectGroup)

# Stats for Total Oyster Density and Total Weight Density by Year and Season and ProjectGroup
QuadStats_ALL_Oys3 <- QuadStats_ALL_Oys %>%
  group_by(Year, 
           Season,
           Season_Year, 
           ProjectGroup) %>%
  summarise_ALL() %>%
  arrange(ProjectGroup, 
          Year, 
          desc(Season))

# Stats for Total Oyster Density and Total Weight Density by Year and Section
QuadStats_ALL_Oys4 <- QuadStats_ALL_Oys %>%
  group_by(Year, 
           SectionName) %>%
  summarise_ALL() %>%
  arrange(Year, 
          SectionName)


```


``` {r OysterStatsby15mmSizeClass}

# Set up

QuadStats_15mmSizeClass_Oys <- QuadStats2 

summarise_15mmSizeClass <- function(data) {
  summarised_data <- data %>%
    summarise(Num_1_to_15_Mean = mean(Num_1_to_15, na.rm = TRUE),
            Num_16_to_30_Mean = mean(Num_16_to_30, na.rm = TRUE),
            Num_31_to_45_Mean = mean(Num_31_to_45, na.rm = TRUE),
            Num_46_to_60_Mean = mean(Num_46_to_60, na.rm = TRUE),
            Num_61_to_75_Mean = mean(Num_61_to_75, na.rm = TRUE),
            Num_76_to_90_Mean = mean(Num_76_to_90, na.rm = TRUE),
            Num_91_plus_Mean = mean(Num_91_plus, na.rm = TRUE)) %>%
    mutate(Density_1_to_15_Mean = Num_1_to_15_Mean * 4,
       Density_16_to_30_Mean = Num_16_to_30_Mean * 4,
       Density_31_to_45_Mean = Num_31_to_45_Mean * 4,
       Density_46_to_60_Mean = Num_46_to_60_Mean * 4,
       Density_61_to_75_Mean = Num_61_to_75_Mean * 4,
       Density_76_to_90_Mean = Num_76_to_90_Mean * 4,
       Density_91_plus_Mean = Num_91_plus_Mean * 4,
       SumDensityMean = Density_1_to_15_Mean + Density_16_to_30_Mean + Density_31_to_45_Mean + Density_46_to_60_Mean + Density_61_to_75_Mean + Density_76_to_90_Mean + Density_91_plus_Mean )
  return(summarised_data)
}

# Stats for Oyster Density by 15mm size class, by Year and ProjectGroup
QuadStats_15mmSizeClass_1 <- QuadStats_15mmSizeClass_Oys %>%
  group_by(Year, 
           ProjectGroup) %>%
  summarise_15mmSizeClass() %>%
  arrange(ProjectGroup, 
          Year)

# Stats for Oyster Density by 15mm size class, by Year and Section and ProjectGroup
QuadStats_15mmSizeClass_2 <- QuadStats_15mmSizeClass_Oys %>%
  group_by(Year, 
           ProjectGroup,
           SectionName) %>%
  summarise_15mmSizeClass() %>%
  arrange(Year, 
          SectionName, 
          ProjectGroup)

# Stats for Oyster Density by 15mm size class, by Year and Season and ProjectGroup
QuadStats_15mmSizeClass_3 <- QuadStats_15mmSizeClass_Oys %>%
  group_by(Year, 
           Season,
           Season_Year, 
           ProjectGroup) %>%
  summarise_15mmSizeClass() %>%
  arrange(ProjectGroup, 
          Year, 
          desc(Season))

# Stats for Oyster Density by 15mm size class, by Year and Section
QuadStats_15mmSizeClass_4 <- QuadStats_15mmSizeClass_Oys %>%
  group_by(Year,
           SectionName) %>%
  summarise_15mmSizeClass() %>%
  arrange(Year, 
          SectionName)

```

``` {r OysterStatsbyClassicSizeClass}

# Set up

QuadStats_ClassicSizeClass_Oys <- QuadStats2 

summarise_ClassicSizeClass <- function(data) {
  summarised_data <- data %>%
    summarise(Num_Spat_1_to_30_Mean = mean(Num_Spat_1_to_30, na.rm = TRUE),
            Num_Seed_31_to_75_Mean = mean(Num_Seed_31_to_75, na.rm = TRUE),
            Num_Legal_76_plus_Mean = mean(Num_Legal_76_plus, na.rm = TRUE)) %>%
    mutate(Density_Spat_1_to_30_Mean = Num_Spat_1_to_30_Mean * 4,
           Density_Seed_31_to_75_Mean = Num_Seed_31_to_75_Mean * 4,
           Density_Legal_76_plus_Mean = Num_Legal_76_plus_Mean * 4,
           SumDensityMean = Density_Spat_1_to_30_Mean + Density_Seed_31_to_75_Mean + Density_Legal_76_plus_Mean)
  return(summarised_data)
}

# Stats for Oyster Density by classic size class, by Year and ProjectGroup
QuadStats_ClassicSizeClass_1 <- QuadStats_ClassicSizeClass_Oys %>%
  group_by(Year, 
           ProjectGroup) %>%
  summarise_ClassicSizeClass() %>%
  arrange(ProjectGroup, 
          Year)

# Stats for Oyster Density by classic size class, by Year and Section and ProjectGroup
QuadStats_ClassicSizeClass_2 <- QuadStats_ClassicSizeClass_Oys %>%
  group_by(Year, 
           ProjectGroup,
           SectionName) %>%
  summarise_ClassicSizeClass() %>%
  arrange(Year, 
          SectionName, 
          ProjectGroup)

# Stats for Oyster Density by classic size class, by Year and Season and ProjectGroup
QuadStats_ClassicSizeClass_3 <- QuadStats_ClassicSizeClass_Oys %>%
  group_by(Year, 
           Season,
           Season_Year, 
           ProjectGroup) %>%
  summarise_ClassicSizeClass() %>%
  arrange(ProjectGroup, 
          Year, 
          desc(Season))

# Stats for Oyster Density by classic size class, by Year and Section
QuadStats_ClassicSizeClass_4 <- QuadStats_ClassicSizeClass_Oys %>%
  group_by(Year,
           SectionName) %>%
  summarise_ClassicSizeClass() %>%
  arrange(Year, 
          SectionName)

```

``` {r LegalOysONLY}

# Set up

QuadStats_LegalONLY_Oys <- QuadStats2 

summarise_LegalONLY <- function(data) {
  summarised_data <- data %>%
    summarise(Num_Legal_76_plus_Mean = mean(Num_Legal_76_plus, na.rm = TRUE),
              Num_Legal_76_plus_SD = sd(Num_Legal_76_plus, na.rm = TRUE)) %>%
    mutate(Density_Legal_76_plus_Mean = Num_Legal_76_plus_Mean * 4,
           Density_Legal_76_plus_SD = Num_Legal_76_plus_SD * 4) %>%
    mutate(BagsPerAcre = (Density_Legal_76_plus_Mean * 4047) / 225,
           BagsPerAcreSD = (Density_Legal_76_plus_SD * 4047) / 225) %>%
    mutate(MaxBags = BagsPerAcre + BagsPerAcreSD,
           MinBags = BagsPerAcre - BagsPerAcreSD)
  return(summarised_data)
}

# Stats for Legal Oyster Density by Year and FixedLocationID
QuadStats_LegalONLY_1 <- QuadStats_LegalONLY_Oys %>%
  group_by(Year, 
           FixedLocationID,
           StationNameNumber,
           TripDate,
           SectionName,
           ProjectGroup) %>%
  summarise_LegalONLY() %>%
  arrange(FixedLocationID, 
          Year)

QuadStats_LegalONLY_Oys_Recent_1 <- QuadStats_LegalONLY_1 %>%
  group_by(FixedLocationID) %>%
  filter(Year >= 2023,
         TripDate == max(TripDate, na.rm = TRUE)) %>%
  ungroup()

# Stats for Total Oyster Density and Total Weight Density by Year and Section and ProjectGroup
QuadStats_LegalONLY_2 <- QuadStats_LegalONLY_Oys %>%
  group_by(Year, 
           ProjectGroup,
           SectionName) %>%
  summarise_LegalONLY() %>%
  arrange(Year, 
          SectionName, 
          ProjectGroup)

##### Not terribly useful
# # Stats for Total Oyster Density and Total Weight Density by Year and Season and ProjectGroup
# QuadStats_LegalONLY_3 <- QuadStats_LegalONLY_Oys %>%
#   group_by(Year, 
#            Season,
#            Season_Year, 
#            ProjectGroup) %>%
#   summarise_LegalONLY() %>%
#   arrange(ProjectGroup, 
#           Year, 
#           desc(Season))

# Stats for Legal Oyster Density by Year and Section
QuadStats_LegalONLY_4 <- QuadStats_LegalONLY_Oys %>%
  group_by(Year,
           SectionName) %>%
  summarise_LegalONLY()

QuadStats_LegalONLY_Oys_Recent_4 <- QuadStats_LegalONLY_4 %>%
  group_by(SectionName) %>%
  filter(Year >= 2023) %>%
  ungroup()

```

``` {r dataExport}
# Temporary section for data export to Excel so I can play around with data / displays to see what we need in the sections following
library(openxlsx)

ALLOysfile = paste("All_Oysters_", Sys.Date(), ".xlsx", sep = "")
SmallSizeClass = paste("Small_Size_Class_", Sys.Date(), ".xlsx", sep = "") 
ClassiciSizeClass = paste("Classic_Size_Class_", Sys.Date(), ".xlsx", sep = "")
LegalONLY = paste("Legal_ONLY_", Sys.Date(), ".xlsx", sep = "")

# All Oysters together
  write.xlsx(list(
    "YearSG" = QuadStats_ALL_Oys1, 
    "YearSectionSG" = QuadStats_ALL_Oys2, 
    "YearSeasonSG" = QuadStats_ALL_Oys3, 
    "YearSection" = QuadStats_ALL_Oys4),
  file = ALLOysfile, colNames = TRUE)
  # Open the workbook for further customization
  wb <- loadWorkbook(ALLOysfile)
  # Auto-adjust column widths
  setColWidths(wb, sheet = "YearSG", cols = 1:ncol(QuadStats_ALL_Oys1), widths = "auto")
  setColWidths(wb, sheet = "YearSectionSG", cols = 1:ncol(QuadStats_ALL_Oys2), widths = "auto")
  setColWidths(wb, sheet = "YearSeasonSG", cols = 1:ncol(QuadStats_ALL_Oys3), widths = "auto")
  setColWidths(wb, sheet = "YearSection", cols = 1:ncol(QuadStats_ALL_Oys4), widths = "auto")
  # Freeze the first row
  freezePane(wb, sheet = "YearSG", firstRow = TRUE)
  freezePane(wb, sheet = "YearSectionSG", firstRow = TRUE)
  freezePane(wb, sheet = "YearSeasonSG", firstRow = TRUE)
  freezePane(wb, sheet = "YearSection", firstRow = TRUE)
  # Save the modified workbook
  saveWorkbook(wb, ALLOysfile, overwrite = TRUE)

  
# Small size classes  (15 mm)
  write.xlsx(list(
    "YearSG" = QuadStats_15mmSizeClass_1, 
    "YearSectionSG" = QuadStats_15mmSizeClass_2, 
    "YearSeasonSG" = QuadStats_15mmSizeClass_3, 
    "YearSection" = QuadStats_15mmSizeClass_4),
  file = SmallSizeClass, colNames = TRUE)
  # Open the workbook for further customization
  wb <- loadWorkbook(SmallSizeClass)
  # Auto-adjust column widths
  setColWidths(wb, sheet = "YearSG", cols = 1:ncol(QuadStats_15mmSizeClass_1), widths = "auto")
  setColWidths(wb, sheet = "YearSectionSG", cols = 1:ncol(QuadStats_15mmSizeClass_2), widths = "auto")
  setColWidths(wb, sheet = "YearSeasonSG", cols = 1:ncol(QuadStats_15mmSizeClass_3), widths = "auto")
  setColWidths(wb, sheet = "YearSection", cols = 1:ncol(QuadStats_15mmSizeClass_4), widths = "auto")
  # Freeze the first row
  freezePane(wb, sheet = "YearSG", firstRow = TRUE)
  freezePane(wb, sheet = "YearSectionSG", firstRow = TRUE)
  freezePane(wb, sheet = "YearSeasonSG", firstRow = TRUE)
  freezePane(wb, sheet = "YearSection", firstRow = TRUE)
  # Save the modified workbook
  saveWorkbook(wb, SmallSizeClass, overwrite = TRUE)
  
  
# Classic size classes  (spat, seed, legal)
  write.xlsx(list(
    "YearSG" = QuadStats_ClassicSizeClass_1, 
    "YearSectionSG" = QuadStats_ClassicSizeClass_2, 
    "YearSeasonSG" = QuadStats_ClassicSizeClass_3, 
    "YearSection" = QuadStats_ClassicSizeClass_4),
  file = ClassiciSizeClass, colNames = TRUE)
  # Open the workbook for further customization
  wb <- loadWorkbook(ClassiciSizeClass)
  # Auto-adjust column widths
  setColWidths(wb, sheet = "YearSG", cols = 1:ncol(QuadStats_ClassicSizeClass_1), widths = "auto")
  setColWidths(wb, sheet = "YearSectionSG", cols = 1:ncol(QuadStats_ClassicSizeClass_2), widths = "auto")
  setColWidths(wb, sheet = "YearSeasonSG", cols = 1:ncol(QuadStats_ClassicSizeClass_3), widths = "auto")
  setColWidths(wb, sheet = "YearSection", cols = 1:ncol(QuadStats_ClassicSizeClass_4), widths = "auto")
  # Freeze the first row
  freezePane(wb, sheet = "YearSG", firstRow = TRUE)
  freezePane(wb, sheet = "YearSectionSG", firstRow = TRUE)
  freezePane(wb, sheet = "YearSeasonSG", firstRow = TRUE)
  freezePane(wb, sheet = "YearSection", firstRow = TRUE)
  # Save the modified workbook
  saveWorkbook(wb, ClassiciSizeClass, overwrite = TRUE)
  
# Legal ONLY
  write.xlsx(list(
    "FixedLocation_Recent" = QuadStats_LegalONLY_Oys_Recent_1,
    "YearSectionPG" = QuadStats_LegalONLY_2,
    "YearSection" = QuadStats_LegalONLY_4), 
    file = LegalONLY, colNames = TRUE)
  # Open the workbook for further customization
  wb <- loadWorkbook(LegalONLY)
  # Auto-adjust column widths
  setColWidths(wb, sheet = "FixedLocation_Recent", cols = 1:ncol(QuadStats_LegalONLY_Oys_Recent_1), widths = "auto")
  setColWidths(wb, sheet = "YearSectionPG", cols = 1:ncol(QuadStats_LegalONLY_2), widths = "auto")
  setColWidths(wb, sheet = "YearSection", cols = 1:ncol(QuadStats_LegalONLY_4), widths = "auto")
  # Freeze the first row
  freezePane(wb, sheet = "FixedLocation_Recent", firstRow = TRUE)
  freezePane(wb, sheet = "YearSectionPG", firstRow = TRUE)
  freezePane(wb, sheet = "YearSection", firstRow = TRUE)
  # Save the modified workbook
  saveWorkbook(wb, LegalONLY, overwrite = TRUE) 
```

```{r Placeholdingstop} 
### Remove this chunk when you are ready to create figures with R
stop("Stopping")
```


```{r FigureFormatting}
#Base formatting for figure consistency
BaseForm <- theme_classic() +
  theme(panel.border = element_rect(color = "black", fill = NA), #Add border
        plot.title = element_text(hjust = 0, vjust = -7, family = "serif", color = "black", size = 12), #Add plot title for section
        axis.title = element_text(family = "serif", color = "black", size = 12), #Adjust axis title and text
        axis.text = element_text(family = "serif", color = "black", size = 10),
        axis.line = element_line(color = "black"),
        axis.ticks.length.x = unit(0.20, "cm"),
        axis.ticks.length.y = unit(0.1, "cm"),
        legend.position = "top", legend.justification = "right",  legend.box.spacing = unit(0.05, "line"), #Adjust legend position
        legend.title = element_blank(), legend.key.height = unit(0.5, "line"), legend.key.width = unit(1, "lines"), #Adjust legend title and spacing
        legend.text = element_text(family = "serif", color = "black", size = 9)) #Adjust legend text

```



```{r PlotFunctions}
# Function to generate grouped bar plots with SD bars
# df is short for data frame
generate_grouped_plot <- function(df, x_variable, x_label, y_variable, y_label, y_SD, UseColor, UseFill, title) {
  
  df <- df %>%
    mutate(Upper = !!sym(y_variable) + !!sym(y_SD))
  max_upper <- max(ungroup(df) %>%
                     dplyr::select(Upper), na.rm = TRUE)
  
  plot_list <- df %>% 
    ggplot(aes(x = factor(!!sym(x_variable), levels = unique(!!sym(x_variable))), 
               y = !!sym(y_variable), 
               color = !!sym(UseColor), 
               fill = as.factor(!!sym(UseFill)))) + 
    geom_bar(stat = "identity", 
             position = position_dodge(width = 0.9),
             color = "black") + 
    geom_errorbar(aes(ymin = !!sym(y_variable), ymax = Upper), 
                  position = position_dodge(width = 0.9), 
                  width = 0.25, color = "black") + 
    scale_x_discrete(x_label, expand = c(0.005, 0), 
                     guide = guide_axis(angle = -45)) +
    scale_y_continuous(y_label, expand = c(0, 0),
                       limits = c(0, ceiling(max_upper * 1.05)),
                       breaks = pretty(0:2 * ceiling(max(ungroup(df) %>% 
                                                         dplyr::select(Upper), na.rm = TRUE) / 2))) + 
    ggtitle(title) + 
    BaseForm +
    theme(legend.position = "bottom",
          plot.title = element_text(hjust = 0, vjust = 0)) 
  
  return(plot_list)
}

```

``` {r New figures}
### Function explanation
# generate_plot(df, x_variable, x_label, y_variable, y_label, y_SD, UseColor, UseFill, title)


# Stats for Total Oyster Density and Total Weight Density by Year and ProjectGroup
# Oysters
QuadStats_ALL_Oys1_fig <- generate_grouped_plot(QuadStats_ALL_Oys1, "Year", "Year", "OysterDensityMean", "Live oysters / m2)", "OysterDensitySD", "ProjectGroup", "ProjectGroup", "AB Oyster Density by Year and ProjectGroup")
print(QuadStats_ALL_Oys1_fig)

# Creating figures Mean Sample Weight Density
QuadStats_ALL_Oys1_Sample_Weight_fig <- generate_grouped_plot(QuadStats_ALL_Oys1, "Year", "Year", "WeightDensityMean", "Sample Weight (kg / m2)", "WeightDensitySD", "ProjectGroup", "ProjectGroup", "AB Sample Weight Density by Year and ProjectGroup")
print(QuadStats_ALL_Oys1_Sample_Weight_fig)




# Stats for Total Oyster Density and Total Weight Density by Year and Section and ProjectGroup
QuadStats_ALL_Oys2_fig <- generate_grouped_plot(QuadStats_ALL_Oys2, "Year", "Year", "OysterDensityMean", "Live oysters / m2)", "OysterDensitySD",  "ProjectGroup", "ProjectGroup", "AB Oyster Density by Year and Section and ProjectGroup")
print(QuadStats_ALL_Oys2_fig)

# Creating figures Mean Sample Weight Density
QuadStats_ALL_Oys2_Sample_Weight_fig <- generate_grouped_plot(QuadStats_ALL_Oys2, "Year", "Year", "WeightDensityMean", "Sample Weight (kg / m2)", "WeightDensitySD", "AB Sample Weight Density by Year and Section and ProjectGroup")
print(QuadStats_ALL_Oys2_Sample_Weight_fig)


```


```{r OG Figures}
# Creating SBM Figures
### Function explanation
# generate_plot(df, x_variable, x_label, y_variable, y_label, y_SD, title)


# Creating Shell Budget figures Mean Live Oysters
SBM_OyDensity <- generate_plot(SBM_QuadStats1, "Survey_Year", "Survey", "OysterDensityMean", "Live oysters / m2)", "OysterDensitySD", "AB SBM Oyster Density")
print(SBM_OyDensity)

# Creating Shell Budget figures Mean live shell heights
SBM_SHLiveMean <- generate_plot(SBM_SHStatsLive, "Survey_Year", "Survey", "SHMean", "Live Shell Height (mm)", "SHSD", "AB SBM Live Shell Heights")
print(SBM_SHLiveMean)

# Creating Shell Budget figures Mean Oyster drill density
SBM_DrillDensity <- generate_plot(SBM_QuadStats1, "Survey_Year", "Survey", "DrillDensityMean", "Live drills / m2)", "DrillDensitySD", "AB SBM Drill Density")
print(SBM_DrillDensity)

#Creating Shell Budget figures Mean Weights
SBM_WeightMean <- generate_plot(SBM_QuadStats1, "Survey_Year", "Survey", "WeightDensityMean", "Mean Weight (kg / m2)", "WeightDensitySD", "AB SBM Weight Density")
print(SBM_WeightMean)

```


```{r Figures}
# Creating Survey Figures
### Function explanation
# generate_plot(df, x_variable, x_label, y_variable, y_label, y_SD, title)

#Filter
Survey_QuadStats2 <- Survey_QuadStats1 %>%
  filter(StationNumber <= 15 & TripDate >= "2020-01-01")
Survey_SHStatsLive2 <- Survey_SHStatsLive %>%
  filter(StationNumber <= 15 & TripDate >= "2020-01-01")

# Creating Surveyfigures Mean Live Oysters
Survey_OyDensity <- generate_plot(Survey_QuadStats2, "Survey_Year", "Survey", "OysterDensityMean", "Live oysters / m2)", "OysterDensitySD", "AB Survey Oyster Density")
print(Survey_OyDensity)

# Creating Surveyfigures Mean live shell heights
Survey_SHLiveMean <- generate_plot(Survey_SHStatsLive2, "Survey_Year", "Survey", "SHMean", "Live Shell Height (mm)", "SHSD", "AB Survey Live Shell Heights")
print(Survey_SHLiveMean)

# Creating Surveyfigures Mean Oyster drill density
Survey_DrillDensity <- generate_plot(Survey_QuadStats2, "Survey_Year", "Survey", "DrillDensityMean", "Live drills / m2)", "DrillDensitySD", "AB Survey Drill Density")
print(Survey_DrillDensity)

#Creating Surveyfigures Mean Weights
Survey_WeightMean <- generate_plot(Survey_QuadStats2, "Survey_Year", "Survey", "WeightDensityMean", "Mean Weight (kg / m2)", "WeightDensitySD", "AB Survey Weight Density")
print(Survey_WeightMean)

```


```{r Component Weights}
#Creating Shell Budget figures Component Weight
datalonag <- SBM_QuadStats2 %>%
  rename_at(vars(ends_with("SD")), ~gsub("SD$", "_SD", .)) %>%
  rename_at(vars(ends_with("Mean")), ~gsub("Mean$", "_Mean", .))

#Combining df of mean values with df of SD values - can remove SD section if desired (left_join() & 475-478)
df_source <- left_join(SBM_QuadStats2 %>% dplyr::select(Survey:StationNumber, ends_with("Mean")) %>% 
                         mutate(StationNameNumber = gsub("SBM ", "", StationNameNumber)) %>%
                         rename_at(vars(ends_with("Mean")), ~gsub("Mean$", "", .)) %>%
                         pivot_longer(cols = ends_with("Weight"), names_to = c("Metric"), values_to = "Mean"),
                       SBM_QuadStats2 %>% dplyr::select(Survey:StationNumber, ends_with("SD")) %>%
                         mutate(StationNameNumber = gsub("SBM ", "", StationNameNumber)) %>%
                         rename_at(vars(ends_with("SD")), ~gsub("SD$", "", .)) %>%
                         pivot_longer(cols = ends_with("Weight"), names_to = c("Metric"), values_to = "SD"))

#max_upper <- max(SBM_QuadStats2 %>%  mutate(Upper = LiveOysterWeightMean + LiveOysterWeightSD) %>% ungroup() %>% dplyr::select(Upper), na.rm = T) ### Based on previous/existing code. Modifying for stacked bar range in next line.
max_upper <- max(df_source %>% group_by(StationNameNumber) %>% summarise(Total = sum(Mean))%>% ungroup() %>% dplyr::select(Total), na.rm = T)

SBM_plot_list <- df_source %>% 
  mutate(Metric= factor(Metric, levels = unique(Metric))) %>%
  ggplot(aes(x = factor(StationNameNumber, levels = unique(StationNameNumber)), 
             y = Mean, 
             color = Metric, 
             fill = as.factor(Metric)))+ 
  geom_bar(stat = "identity", 
           position = "stack",
           color = "black") + 
  scale_x_discrete("Station", expand = c(0.005, 0), 
                 guide = guide_axis(angle = 45))+
  scale_y_continuous(expression("Component Weight (kg/m"^2*")"), expand = c(0, 0),
                   limits = c(0, ceiling(max_upper * 1.05)), #Provides a 5% buffer to the top of bars
                   breaks = pretty(0:2 * ceiling(max_upper/2))) + 
  ggtitle("AB SBM Oy Weights") + 
  BaseForm +
  theme(legend.position = "bottom",
        plot.title = element_text(hjust = 0, vjust = 0))

print(SBM_plot_list)

```

```{r}
# library(openxlsx)
# 
knit_exit()

# mydatasets <- list('Sheet1' = SBM_QuadStats1, 'Sheet2' = SBM_QuadStats2, 'Sheet3' = SBM_SHStatsLive, 'Sheet4' = SBM_SHStatsDead)
# write.xlsx(mydatasets, "SBM_ReportStats.xlsx", colNames = TRUE, rowNames = FALSE)
# 
```
