---
title: "Annual Report Analyses Setup"
author: "EWilliams"
date: "`r Sys.Date()`"
output: html_document
params:
  Start_date: "2023-10-01"
  End_date: "2024-09-30"
  Excel_name: "CERP_2025"

knit: (function(inputFile, encoding) {
  rmarkdown::render(
    input = inputFile, 
    encoding = encoding,
    output_file = paste0(substr(inputFile, 1, nchar(inputFile)-4), " - ", with(rmarkdown::yaml_front_matter(inputFile), paste(params$Excel_name)), '.html')
    ) 
      })
---

<!-- This file applies the best models and outputs report analyses. Models of best fit need to be updated in the following lines:
  Survey: 240, 340, and 423
  Dermo: 527 and 616
  Rcrt: 715
  Sal: 811
  Flow: 907

## Work flow: 
 Use fit_model to chose best distribution
 Fit best model using lmer to get SAS style output
   If NB but no random - lme4::glm.nb
   If NB with random - MASS::glmer.nb
-->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
#
Summary_Excel_file_name <- params$Excel_name
Estuary_code <- c("CR", "SL", "LX")
Start_date <- as.Date(params$Start_date)
End_date <- as.Date(params$End_date)
Flow_sites <- c("SL", "LX", "CR")
sheet_lookup <- c(SL = "SLESum", LX = "LOXSum", CR = "S79")
#
#Packages
if (!require("pacman")) {install.packages("pacman")}
#p_unlock()
pacman::p_load(odbc, DBI, dbplyr,
  tidyverse, dplyr,  stringr, #DF manipulation
  DT, openxlsx, readxl,        #Excel
  lubridate, zoo,         #Dates
  glmmTMB, purrr, emmeans, car, broom, multcomp, lmerTest,#Analyses
  knitr, kableExtra, scales, gt, gtExtras,
  install = TRUE)
#
#
```

```{css}
p {
font-size: 12pt;
}

caption {
  color: black;
  font-weight: bold;
  font-size: 14;
  text-indent: 5%;
} 

h1 {
font-size: 21pt;
font-weight: bold;
}

h2 {
font-size: 17pt;
font-weight: bold;
}

h3 {
font-size: 13pt;
font-style: italic;
text-decoration: underline;
}

h4 {
  color: black;
  font-weight: bold;
  font-size: 17;
  text-indent: 5%;
}
```

```{r Data gather from raw data file, include = FALSE}
# Survey data set up:
Counts_df <- readWorkbook("../Data/CERP_PBC_Raw_Data.xlsx", sheet = 'SrvyCounts', detectDates = TRUE, check.names = TRUE) %>% mutate(RetDate = as.Date(RetDate, "%m/%d/%Y")) %>% 
  subset(RetDate > (Start_date %m-% months(2)) & RetDate < (End_date %m+% months(1))) %>%
  # Filter to CERP sites
  filter(Site %in% c("SL-N", "SL-C", "SL-S", "LX-N", "LX-S", "CR-E", "CR-W")) %>%
  # Remove TIG samples in Winter/Summer
  filter(!(
      grepl("Winter|Summer", Survey) &
      Site %in% c("CR-E", "CR-W") &
      Station %in% c(1, 4)
    )) %>%
  # Calculate Live/Dead per meter2
  mutate(
    Live = NumLive * 4,
    Dead = NumDead * 4,
    Total = Live+Dead,
    SurvCode_n = case_when(
      Survey == "Winter 2023" ~ 0.5,
      Survey == "Spring 2024" ~ 1,
      Survey == "Summer 2024"   ~ 1.5,
      Survey == "Fall 2024" ~ 2,
      TRUE ~ NA_real_)) %>%
  # Make sure columns are factors
  mutate(across(c(Site, Station), as.factor)) %>%
  mutate(SurvCode = as.factor(SurvCode_n),
         DeadRatio = Dead/Total) %>% 
  mutate(Live = ifelse(Live < 0, NA, Live),
         Dead = ifelse(Dead < 0, NA, Dead)) %>% 
    arrange(Site, Station, SurvCode)
#
#
SH_df <- readWorkbook("../Data/CERP_PBC_Raw_Data.xlsx", sheet = 'SrvySHs', detectDates = TRUE, check.names = TRUE)  %>% mutate(RetDate = as.Date(RetDate, "%m/%d/%Y")) %>% 
  subset(RetDate > (Start_date %m-% months(2)) & RetDate < (End_date %m+% months(1))) %>%
  mutate(across(ShellHeight, ~ replace_na(.x, -999))) %>%
  # Filter to CERP sites
  filter(Site %in% c("SL-N", "SL-C", "SL-S", "LX-N", "LX-S", "CR-E", "CR-W")) %>%
  # Remove TIG samples in Winter/Summer
  filter(!(
      str_detect(Survey %||% "", "Winter|Summer") &
      Site %in% c("CR-E", "CR-W") &
      Station %in% c(1, 4)
    )) %>%
  mutate(SurvCode = as.factor(case_when(
    Survey == "Winter 2034" ~ 0.5,
    Survey == "Spring 2024" ~ 1,
    Survey == "Summer 2024"   ~ 1.5,
    Survey == "Fall 2024" ~ 2,
    TRUE ~ NA_real_))) %>%
  # Make sure columns are factors
  mutate(across(c(Site, Station), as.factor)) %>%
  mutate(ShellHeight = ifelse(ShellHeight < 0, NA, ShellHeight))
#
#
#
## Dermo
Dermo_df <- readWorkbook("../Data/CERP_PBC_Raw_Data.xlsx", sheet = 'Dermo', detectDates = TRUE, check.names = TRUE) %>% 
  mutate(RetDate = as.Date(RetDate, "%m/%d/%Y"),
         AnalysisDate = as.factor(update(RetDate, mday = 15)),
         time = as.numeric(as.factor(AnalysisDate))) %>% 
  subset(RetDate > Start_date & RetDate < End_date) %>%
  # Filter to CERP sites
  filter(Site %in% c("SL-N", "SL-C", "SL-S", "LX-N", "LX-S", "CR-E", "CR-W")) %>%
  # Determine mean dermo and deamo presence
  mutate(MeanDermo = rowMeans(across(c(DermoMantle, DermoGill)), na.rm = T),
         DermoSum = rowSums(across(c(DermoMantle, DermoGill)), na.rm = T)) %>%
  mutate(DermoSum = case_when(DermoSum > 0 ~ 1, 
                              DermoSum == 0 ~ 0, 
                              TRUE ~ NA)) %>%
  mutate(across(c(Site, Station), as.factor))
#
#
## Rcrt
Rcrt_df <- readWorkbook("../Data/CERP_PBC_Raw_Data.xlsx", sheet = 'Rcrt', detectDates = TRUE, check.names = TRUE) %>%
  mutate(RetDate = as.Date(RetDate, "%m/%d/%Y"),
         AnalysisDate = as.factor(update(RetDate, mday = 15)),
         time = as.numeric(as.factor(AnalysisDate))) %>% 
  subset(RetDate > Start_date & RetDate < End_date) %>%
  # Filter to CERP sites
  filter(Site %in% c("SL-N", "SL-C", "SL-S", "LX-N", "LX-S", "CR-E", "CR-W")) %>%
  # Remove spat for top and bottom shells
  mutate(Bottom = case_when(grepl("SL|LX", Site) & Shell %in% c(1, 6, 7, 12) ~ NA_real_, 
                            Site %in% c("CR-E", "CR-W") & Shell %in% c(1, 12) ~ NA_real_, 
                            TRUE ~ NumBottom)) %>%
  mutate(BottomMonth = Bottom/(DaysDeployed/28)) %>%
  mutate(across(c(Site, Station, Rep, Shell), as.factor)) %>%
  arrange(RetDate)
#
#
## Salinity
Sal_df <- readWorkbook("../Data/CERP_PBC_Raw_Data.xlsx", sheet = 'WaterQuality', detectDates = TRUE, check.names = TRUE) %>%
  dplyr::select(Year:Station, Sal) %>% 
  mutate(RetDate = as.Date(RetDate, "%m/%d/%Y"),
         AnalysisDate = as.factor(update(RetDate, mday = 15)),
         time = as.numeric(as.factor(AnalysisDate))) %>% 
  subset(RetDate > Start_date & RetDate < End_date) %>%
  # Filter to CERP sites
  filter(Site %in% c("SL-N", "SL-C", "SL-S", "LX-N", "LX-S", "CR-E", "CR-W")) %>%
  mutate(across(c(Site, Station), as.factor)) %>%
  arrange(RetDate)
#
#
## FLOW
# Compile file names and load into one df
files <- file.path("../DBHYDRO/Shared_data", paste0(Flow_sites, "_Flow.xlsx"))
flow_list <- map2(
  files,
  sheet_lookup[Flow_sites],
  ~ read_excel(.x, sheet = .y)
)
flow_list_long <- imap(flow_list, ~
  .x %>%
    dplyr::select(-any_of(c("DBKEY", "Site", "Data_Station"))) %>%   # safely remove if present
    pivot_longer(
      cols = -c(Analysis_Date, Date, Estuary),
      names_to = "Station",
      values_to = "Flow"
    )
)
flow_df <- bind_rows(flow_list_long) %>%
  mutate(Year = format(Analysis_Date, format = "%Y"),
         AnalysisDate = as.factor(update(Analysis_Date, mday = 15)),
         time = as.numeric(as.factor(AnalysisDate))) %>%
  filter(Station %in% c("SLESum", "LOXSum", "Flow")) %>%
  rename("Site" = Estuary) %>%
  mutate(across(c(Site, Station, Year), as.factor)) 

#
rm(files, flow_list, flow_list_long)

#
#
#
```

```{r Survey analyses}
#
## Testing for differences between sites and months
#
# Limit to spring and fall
Counts2 <- Counts_df %>% 
  filter(SurvCode == 1 | SurvCode == 2) %>% droplevels() %>%
  arrange(Site, Station, SurvCode)
#
### Live counts:
# Fit best model: No random, NB
Live_model <- MASS::glm.nb(Live ~ Site * SurvCode, data = Counts2)
#
#
Live_anova <- Anova(Live_model, type = 3, test.statistic = "F") %>% #best_model$model
  as.data.frame() %>%
  tibble::rownames_to_column("Effect") %>%
  rename(
    `Num DF` = Df
  ) %>%
  filter(Effect != "Residuals") %>%
  mutate(`Den Df` = df.residual(Live_model)) %>%
  dplyr::select(Effect, `Num DF`, `Den Df`, `F values`, `Pr(>F)`)
#
Live_anova %>% gt() %>% 
  tab_header(title = "Survey Live Counts")
#
# LSMeans
Live_site_table <- left_join(
  summary(emmeans(Live_model, ~ Site), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(Live_model, ~ Site, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, response, SE) %>%
    rename("Mean" = response, "SE Mean" = SE))
#
#
Live_surv_table <- left_join(
  summary(emmeans(Live_model, ~ SurvCode), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(SurvCode, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(Live_model, ~ SurvCode, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(SurvCode, response, SE) %>%
    rename("Mean" = response, "SE Mean" = SE))
# 
Live_surv_table %>% gt()
#
Live_int_table <- left_join(
  summary(emmeans(Live_model, ~ Site * SurvCode), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, SurvCode, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(Live_model, ~ Site * SurvCode, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, SurvCode, response, SE) %>%
    rename("Mean" = response, "SE Mean" = SE))
#
#
# Letters
Live_cld_site <- multcomp::cld(
  emmeans(Live_model, ~ Site),
  Letters = letters,
  adjust = "sidak"
)
Live_cld_site_table <- as.data.frame(Live_cld_site) %>%
  dplyr::select(Site, emmean, .group) %>%
  arrange(desc(emmean)) %>%
  rename(
    Estimate = emmean,
    Group = .group
  )
#
left_join(Live_site_table, Live_cld_site_table) %>% gt()
Live_cld_site_table %>% gt()
#
Live_cld_int <- multcomp::cld(
  emmeans(Live_model, ~ Site * SurvCode),
  Letters = letters,
  adjust = "sidak"
)
Live_cld_int_table <- as.data.frame(Live_cld_int) %>%
  dplyr::select(Site, SurvCode, emmean, .group) %>%
  arrange(desc(emmean)) %>%
  rename(
    Estimate = emmean,
    Group = .group
  )
#
left_join(Live_int_table, Live_cld_int_table) %>% gt()
Live_cld_int_table %>% gt()
#
#
#
#
### Dead Ratio:
# Fit best model: Site Random
Dead_model <- glmmTMB(DeadRatio ~ Site * SurvCode + (1 | Site/Station), 
                      family = "binomial", data = Counts2)
#
#
Dead_anova <- joint_tests(Dead_model) %>% 
  as.data.frame() %>%
  rename(
    "Effect" = `model term`
  ) %>%
  mutate(df2 = nobs(Dead_model) - length(fixef(Dead_model)$cond))#For glmmTMB
#
Dead_anova %>% gt() %>% 
  tab_header(title = "Survey Dead Ratios")
#
# LSMeans
Dead_site_table <- left_join(
  summary(emmeans(Dead_model, ~ Site), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(Dead_model, ~ Site, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, prob, SE) %>%
    rename("Mean" = prob, "SE Mean" = SE))
#
# 
Dead_surv_table <- left_join(
  summary(emmeans(Dead_model, ~ SurvCode), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(SurvCode, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(Dead_model, ~ SurvCode, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(SurvCode, prob, SE) %>%
    rename("Mean" = prob, "SE Mean" = SE))
# 
Dead_surv_table %>% gt()
#
Dead_int_table <- left_join(
  summary(emmeans(Dead_model, ~ Site * SurvCode), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, SurvCode, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(Dead_model, ~ Site * SurvCode, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, SurvCode, prob, SE) %>%
    rename("Mean" = prob, "SE Mean" = SE))
#
#
# Letters
Dead_cld_site <- multcomp::cld(
  emmeans(Dead_model, ~ Site),
  Letters = letters,
  adjust = "sidak"
)
Dead_cld_site_table <- as.data.frame(Dead_cld_site) %>%
  dplyr::select(Site, emmean, .group) %>%
  arrange(desc(emmean)) %>%
  rename(
    Estimate = emmean,
    Group = .group
  )
#
left_join(Dead_site_table, Dead_cld_site_table) %>% gt()
Dead_cld_site_table %>% gt()
#
Dead_cld_int <- multcomp::cld(
  emmeans(Dead_model, ~ Site * SurvCode),
  Letters = letters,
  adjust = "sidak"
)
Dead_cld_int_table <- as.data.frame(Dead_cld_int) %>%
  dplyr::select(Site, SurvCode, emmean, .group) %>%
  arrange(desc(emmean)) %>%
  rename(
    Estimate = emmean,
    Group = .group
  )
#
left_join(Dead_int_table, Dead_cld_int_table) %>% gt()
Dead_cld_int_table %>% gt()
#
#
#
### Shell Heights
SH2 <- SH_df %>% 
  filter(SurvCode == 1 | SurvCode == 2) %>% droplevels() %>%
  group_by(Site, SurvCode, Station, Quadrat) %>%
  # Calculate mean SH per quadrat 
  summarise(MeanSH = mean(ShellHeight, na.rm = T), .groups = "drop") %>%
  
  arrange(Site, SurvCode, Station)
#
# Fit best model: No random, NB
Shel_model <- MASS::glm.nb(MeanSH ~ Site * SurvCode, data = SH2)
#
#
Shel_anova <- Anova(Shel_model, type = 3, test.statistic = "F") %>% #best_model$model
  as.data.frame() %>%
  tibble::rownames_to_column("Effect") %>%
  rename(
    `Num DF` = Df
  ) %>%
  filter(Effect != "Residuals") %>%
  mutate(`Den Df` = df.residual(Shel_model)) %>%
  dplyr::select(Effect, `Num DF`, `Den Df`, `F values`, `Pr(>F)`)
#
Shel_anova %>% gt() %>% 
  tab_header(title = "Survey Shell Heights")
#
# LSMeans
Shel_site_table <- left_join(
  summary(emmeans(Shel_model, ~ Site), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(Shel_model, ~ Site, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, response, SE) %>%
    rename("Mean" = response, "SE Mean" = SE))
#
#
Shel_surv_table <- left_join(
  summary(emmeans(Shel_model, ~ SurvCode), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(SurvCode, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(Shel_model, ~ SurvCode, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(SurvCode, response, SE) %>%
    rename("Mean" = response, "SE Mean" = SE))
# 
Shel_surv_table %>% gt()
#
Shel_int_table <- left_join(
  summary(emmeans(Shel_model, ~ Site * SurvCode), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, SurvCode, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(Shel_model, ~ Site * SurvCode, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, SurvCode, response, SE) %>%
    rename("Mean" = response, "SE Mean" = SE))
#
#
# Letters
Shel_cld_site <- multcomp::cld(
  emmeans(Shel_model, ~ Site),
  Letters = letters,
  adjust = "sidak"
)
Shel_cld_site_table <- as.data.frame(Shel_cld_site) %>%
  dplyr::select(Site, emmean, .group) %>%
  arrange(desc(emmean)) %>%
  rename(
    Estimate = emmean,
    Group = .group
  )
#
left_join(Shel_site_table, Shel_cld_site_table) %>% gt()
Shel_cld_site_table %>% gt()
#
Shel_cld_int <- multcomp::cld(
  emmeans(Shel_model, ~ Site * SurvCode),
  Letters = letters,
  adjust = "sidak"
)
Shel_cld_int_table <- as.data.frame(Shel_cld_int) %>%
  dplyr::select(Site, SurvCode, emmean, .group) %>%
  arrange(desc(emmean)) %>%
  rename(
    Estimate = emmean,
    Group = .group
  )
#
left_join(Shel_int_table, Shel_cld_int_table) %>% gt()
Shel_cld_int_table %>% gt()
#
#
#
#
```

```{r Dermo analyses}
#
#
Dermo2 <- Dermo_df %>% 
  # Calculate mean dermo per month per station
  group_by(AnalysisDate, time, Site, Station) %>%
  summarise(MeanDermo = mean(MeanDermo, na.rm = T),
            Infected = sum(DermoSum),
            N = n(),
            .groups = "drop") %>%
  mutate(DermoPrev = Infected/N) %>%
  arrange(Site, Station, AnalysisDate, time) 
#
### Intensity:
# Fit best model: No random, NB
DInt_model <- MASS::glm.nb(MeanDermo ~ Site * AnalysisDate, data = Dermo_df)
#
#
DInt_anova <- Anova(DInt_model, type = 3, test.statistic = "F") %>% #best_model$model
  as.data.frame() %>%
  tibble::rownames_to_column("Effect") %>%
  rename(
    `Num DF` = Df
  ) %>%
  filter(Effect != "Residuals") %>%
  mutate(`Den Df` = df.residual(DInt_model)) %>%
  dplyr::select(Effect, `Num DF`, `Den Df`, `F values`, `Pr(>F)`)
#
DInt_anova %>% gt() %>% 
  tab_header(title = "Dermo Intensity")
#
# LSMeans
DInt_site_table <- left_join(
  summary(emmeans(DInt_model, ~ Site), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(DInt_model, ~ Site, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, response, SE) %>%
    rename("Mean" = response, "SE Mean" = SE))
#
#
DInt_surv_table <- left_join(
  summary(emmeans(DInt_model, ~ AnalysisDate), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(AnalysisDate, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(DInt_model, ~ AnalysisDate, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(AnalysisDate, response, SE) %>%
    rename("Mean" = response, "SE Mean" = SE))
# 
DInt_surv_table %>% gt()
#
DInt_int_table <- left_join(
  summary(emmeans(DInt_model, ~ Site * AnalysisDate), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, AnalysisDate, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(DInt_model, ~ Site * AnalysisDate, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, AnalysisDate, response, SE) %>%
    rename("Mean" = response, "SE Mean" = SE))
#
#
# Letters
DInt_cld_site <- multcomp::cld(
  emmeans(DInt_model, ~ Site),
  Letters = letters,
  adjust = "sidak"
)
DInt_cld_site_table <- as.data.frame(DInt_cld_site) %>%
  dplyr::select(Site, emmean, .group) %>%
  arrange(desc(emmean)) %>%
  rename(
    Estimate = emmean,
    Group = .group
  )
#
left_join(DInt_site_table, DInt_cld_site_table) %>% gt()
DInt_cld_site_table %>% gt()
#
DInt_cld_int <- multcomp::cld(
  emmeans(DInt_model, ~ Site * AnalysisDate),
  Letters = letters,
  adjust = "sidak"
)
DInt_cld_int_table <- as.data.frame(DInt_cld_int) %>%
  dplyr::select(Site, AnalysisDate, emmean, .group) %>%
  arrange(desc(emmean)) %>%
  rename(
    Estimate = emmean,
    Group = .group
  )
#
left_join(DInt_int_table, DInt_cld_int_table) %>% gt()
DInt_cld_int_table %>% gt()
#
#
#
#
### Prevalence:
# Fit best model: Site Random
DPre_model <- glmmTMB(DermoPrev ~ Site * AnalysisDate, 
                      family = "binomial", data = Dermo2)
#
#
DPre_anova <- joint_tests(DPre_model) %>% 
  as.data.frame() %>%
  rename(
    "Effect" = `model term`
  ) %>%
  mutate(df2 = nobs(DPre_model) - length(fixef(DPre_model)$cond))#For glmmTMB
#
DPre_anova %>% gt() %>% 
  tab_header(title = "Dermo Prevalence")
#
# LSMeans
DPre_site_table <- left_join(
  summary(emmeans(DPre_model, ~ Site), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(DPre_model, ~ Site, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, prob, SE) %>%
    rename("Mean" = prob, "SE Mean" = SE))
#
#
DPre_surv_table <- left_join(
  summary(emmeans(DPre_model, ~ AnalysisDate), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(AnalysisDate, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(DPre_model, ~ AnalysisDate, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(AnalysisDate, prob, SE) %>%
    rename("Mean" = prob, "SE Mean" = SE))
# 
DPre_surv_table %>% gt()
#
DPre_int_table <- left_join(
  summary(emmeans(DPre_model, ~ Site * AnalysisDate), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, AnalysisDate, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(DPre_model, ~ Site * AnalysisDate, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, AnalysisDate, prob, SE) %>%
    rename("Mean" = prob, "SE Mean" = SE))
#
#
# Letters
DPre_cld_site <- multcomp::cld(
  emmeans(DPre_model, ~ Site),
  Letters = letters,
  adjust = "sidak"
)
DPre_cld_site_table <- as.data.frame(DPre_cld_site) %>%
  dplyr::select(Site, emmean, .group) %>%
  arrange(desc(emmean)) %>%
  rename(
    Estimate = emmean,
    Group = .group
  )
#
left_join(DPre_site_table, DPre_cld_site_table) %>% gt()
DPre_cld_site_table %>% gt()
#
DPre_cld_int <- multcomp::cld(
  emmeans(DPre_model, ~ Site * AnalysisDate),
  Letters = letters,
  adjust = "sidak"
)
DPre_cld_int_table <- as.data.frame(DPre_cld_int) %>%
  dplyr::select(Site, AnalysisDate, emmean, .group) %>%
  arrange(desc(emmean)) %>%
  rename(
    Estimate = emmean,
    Group = .group
  )
#
left_join(DPre_int_table, DPre_cld_int_table) %>% gt()
DPre_cld_int_table %>% gt()
#
#
#
```

```{r Recruitment analyses}
#
#
Rcrt2 <- Rcrt_df %>% 
  # Calculate mean per rep for each station 
  group_by(AnalysisDate, time, Site, Station, Rep) %>%
  mutate(AnalysisDate = as.factor(AnalysisDate)) %>%
  # Calculate mean monthly recruitment
  summarise(BottomMonth_mean = mean(BottomMonth, na.rm = T), .groups = "drop") %>%
  arrange(Site, Station, AnalysisDate, time)
#
### Intensity:
# Fit best model: No random, NB
Rcrt_model <- glm(BottomMonth_mean ~ Site * AnalysisDate, family = "poisson", data = Rcrt2)
#
#
Rcrt_anova <- Anova(Rcrt_model, type = 3, test.statistic = "F") %>% #best_model$model
  as.data.frame() %>%
  tibble::rownames_to_column("Effect") %>%
  rename(
    `Num DF` = Df
  ) %>%
  filter(Effect != "Residuals") %>%
  mutate(`Den Df` = df.residual(Rcrt_model)) %>%
  dplyr::select(Effect, `Num DF`, `Den Df`, `F values`, `Pr(>F)`)
#
Rcrt_anova %>% gt() %>% 
  tab_header(title = "Recruitment")
#
# LSMeans
Rcrt_site_table <- left_join(
  summary(emmeans(Rcrt_model, ~ Site), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(Rcrt_model, ~ Site, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, rate, SE) %>%
    rename("Mean" = rate, "SE Mean" = SE))
#
#
Rcrt_surv_table <- left_join(
  summary(emmeans(Rcrt_model, ~ AnalysisDate), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(AnalysisDate, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(Rcrt_model, ~ AnalysisDate, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(AnalysisDate, rate, SE) %>%
    rename("Mean" = rate, "SE Mean" = SE))
# 
Rcrt_surv_table %>% gt()
#
Rcrt_int_table <- left_join(
  summary(emmeans(Rcrt_model, ~ Site * AnalysisDate), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, AnalysisDate, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(Rcrt_model, ~ Site * AnalysisDate, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, AnalysisDate, rate, SE) %>%
    rename("Mean" = rate, "SE Mean" = SE))
#
#
# Letters
Rcrt_cld_site <- multcomp::cld(
  emmeans(Rcrt_model, ~ Site),
  Letters = letters,
  adjust = "sidak"
)
Rcrt_cld_site_table <- as.data.frame(Rcrt_cld_site) %>%
  dplyr::select(Site, emmean, .group) %>%
  arrange(desc(emmean)) %>%
  rename(
    Estimate = emmean,
    Group = .group
  )
#
left_join(Rcrt_site_table, Rcrt_cld_site_table) %>% gt()
Rcrt_cld_site_table %>% gt()
#
Rcrt_cld_int <- multcomp::cld(
  emmeans(Rcrt_model, ~ Site * AnalysisDate),
  Letters = letters,
  adjust = "sidak"
)
Rcrt_cld_int_table <- as.data.frame(Rcrt_cld_int) %>%
  dplyr::select(Site, AnalysisDate, emmean, .group) %>%
  arrange(desc(emmean)) %>%
  rename(
    Estimate = emmean,
    Group = .group
  )
#
left_join(Rcrt_int_table, Rcrt_cld_int_table) %>% gt()
Rcrt_cld_int_table %>% gt()
#
#
#
#
```

```{r Salinity analyses}
#
#
Sal2 <- Sal_df %>% 
  arrange(Site, Station, AnalysisDate, time)
#
# Fit best model: No random, NB
Sali_model <- MASS::glm.nb(Sal ~ Site * AnalysisDate, data = Sal2)
#
#
Sali_anova <- Anova(Sali_model, type = 3, test.statistic = "F") %>% #best_model$model
  as.data.frame() %>%
  tibble::rownames_to_column("Effect") %>%
  rename(
    `Num DF` = Df
  ) %>%
  filter(Effect != "Residuals") %>%
  mutate(`Den Df` = df.residual(Sali_model)) %>%
  dplyr::select(Effect, `Num DF`, `Den Df`, `F values`, `Pr(>F)`)
#
Sali_anova %>% gt() %>% 
  tab_header(title = "Salinity")
#
# LSMeans
Sali_site_table <- left_join(
  summary(emmeans(Sali_model, ~ Site), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(Sali_model, ~ Site, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, response, SE) %>%
    rename("Mean" = response, "SE Mean" = SE))
#
#
Sali_surv_table <- left_join(
  summary(emmeans(Sali_model, ~ AnalysisDate), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(AnalysisDate, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(Sali_model, ~ AnalysisDate, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(AnalysisDate, response, SE) %>%
    rename("Mean" = response, "SE Mean" = SE))
# 
Sali_surv_table %>% gt()
#
Sali_int_table <- left_join(
  summary(emmeans(Sali_model, ~ Site * AnalysisDate), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, AnalysisDate, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(Sali_model, ~ Site * AnalysisDate, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, AnalysisDate, response, SE) %>%
    rename("Mean" = response, "SE Mean" = SE))
#
#
# Letters
Sali_cld_site <- multcomp::cld(
  emmeans(Sali_model, ~ Site),
  Letters = letters,
  adjust = "sidak"
)
Sali_cld_site_table <- as.data.frame(Sali_cld_site) %>%
  dplyr::select(Site, emmean, .group) %>%
  arrange(desc(emmean)) %>%
  rename(
    Estimate = emmean,
    Group = .group
  )
#
left_join(Sali_site_table, Sali_cld_site_table) %>% gt()
Sali_cld_site_table %>% gt()
#
Sali_cld_int <- multcomp::cld(
  emmeans(Sali_model, ~ Site * AnalysisDate),
  Letters = letters,
  adjust = "sidak"
)
Sali_cld_int_table <- as.data.frame(Sali_cld_int) %>%
  dplyr::select(Site, AnalysisDate, emmean, .group) %>%
  arrange(desc(emmean)) %>%
  rename(
    Estimate = emmean,
    Group = .group
  )
#
left_join(Sali_int_table, Sali_cld_int_table) %>% gt()
Sali_cld_int_table %>% gt()
#
#
#
#
```

```{r Flow analyses}
#
#
Flow2 <- flow_df %>% 
  arrange(Year, Site, AnalysisDate, time)
#
# Fit best model: No random, NB
Flow_model <- MASS::glm.nb(Flow ~ Site * Year, data = Flow2)
#
#
Flow_anova <- Anova(Flow_model, type = 3, test.statistic = "F") %>% #best_model$model
  as.data.frame() %>%
  tibble::rownames_to_column("Effect") %>%
  rename(
    `Num DF` = Df
  ) %>%
  filter(Effect != "Residuals") %>%
  mutate(`Den Df` = df.residual(Flow_model)) %>%
  dplyr::select(Effect, `Num DF`, `Den Df`, `F values`, `Pr(>F)`)
#
Flow_anova %>% gt() %>% 
  tab_header(title = "Flow")
#
# LSMeans
Flow_site_table <- left_join(
  summary(emmeans(Flow_model, ~ Site), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(Flow_model, ~ Site, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, response, SE) %>%
    rename("Mean" = response, "SE Mean" = SE))
#
#
Flow_surv_table <- left_join(
  summary(emmeans(Flow_model, ~ Year), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(Year, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(Flow_model, ~ Year, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(Year, response, SE) %>%
    rename("Mean" = response, "SE Mean" = SE))
# 
Flow_surv_table %>% gt()
#
Flow_int_table <- left_join(
  summary(emmeans(Flow_model, ~ Site * Year), infer = TRUE) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, Year, emmean, SE, z.ratio, p.value) %>%
    rename("Estimate" = emmean, "t Value" = z.ratio, "Pr > [t]" = p.value),
  summary(emmeans(Flow_model, ~ Site * Year, type = "response")) %>% 
    as.data.frame() %>% 
    dplyr::select(Site, Year, response, SE) %>%
    rename("Mean" = response, "SE Mean" = SE))
#
#
# Letters
Flow_cld_site <- multcomp::cld(
  emmeans(Flow_model, ~ Site),
  Letters = letters,
  adjust = "sidak"
)
Flow_cld_site_table <- as.data.frame(Flow_cld_site) %>%
  dplyr::select(Site, emmean, .group) %>%
  arrange(desc(emmean)) %>%
  rename(
    Estimate = emmean,
    Group = .group
  )
#
left_join(Flow_site_table, Flow_cld_site_table) %>% gt()
Flow_cld_site_table %>% gt()
#
Flow_cld_year <- multcomp::cld(
  emmeans(Flow_model, ~ Year),
  Letters = letters,
  adjust = "sidak"
)
Flow_cld_year_table <- as.data.frame(Flow_cld_year) %>%
  dplyr::select(Year, emmean, .group) %>%
  arrange(desc(emmean)) %>%
  rename(
    Estimate = emmean,
    Group = .group
  )
#
left_join(Flow_surv_table, Flow_cld_year_table) %>% gt()
Flow_cld_year_table %>% gt()
#
Flow_cld_int <- multcomp::cld(
  emmeans(Flow_model, ~ Site * Year),
  Letters = letters,
  adjust = "sidak"
)
Flow_cld_int_table <- as.data.frame(Flow_cld_int) %>%
  dplyr::select(Site, Year, emmean, .group) %>%
  arrange(desc(emmean)) %>%
  rename(
    Estimate = emmean,
    Group = .group
  )
#
left_join(Flow_int_table, Flow_cld_int_table) %>% gt()
Flow_cld_int_table %>% gt()
#
#
#
#
```

```{r Excel output, inlcude = FALSE}
#
file_path <- paste0("../CERP/", Summary_Excel_file_name, ".xlsx")
bold_header_style <- createStyle(textDecoration = "Bold")

# If file exists, load it; otherwise create a new workbook
if (file.exists(file_path)) {
  wb <- loadWorkbook(file_path)
} else {
  wb <- createWorkbook()
}
#
## Survey Live counts
sheet_name <- "Live"
# Check if the sheet already exists
if (!(sheet_name %in% names(wb))) {
    addWorksheet(wb, sheet_name)
} 
#
writeData(wb, sheet = sheet_name, x = Live_anova, startCol = 1, startRow = 4, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = left_join(Live_site_table, Live_cld_site_table), startCol = 1, startRow = 10, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = Live_surv_table, startCol = 1, startRow = 21, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = left_join(Live_int_table,Live_cld_int_table), startCol = 1, startRow = 26, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = Live_cld_site_table, startCol = 10, startRow = 10, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = Live_cld_int_table, startCol = 11, startRow = 26, headerStyle = bold_header_style)
#
#
## Survey Dead
sheet_name <- "Dead Ratio"
# Check if the sheet already exists
if (!(sheet_name %in% names(wb))) {
    addWorksheet(wb, sheet_name)
}
writeData(wb, sheet = sheet_name, x = Dead_anova, startCol = 1, startRow = 4, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = left_join(Dead_site_table, Dead_cld_site_table), startCol = 1, startRow = 10, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = Dead_surv_table, startCol = 1, startRow = 21, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = left_join(Dead_int_table, Dead_cld_int_table), startCol = 1, startRow = 26, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = Dead_cld_site_table, startCol = 10, startRow = 10, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = Dead_cld_int_table, startCol = 11, startRow = 26, headerStyle = bold_header_style)
#
#
## Survey Shell heights
sheet_name <- "SH"
# Check if the sheet already exists
if (!(sheet_name %in% names(wb))) {
    addWorksheet(wb, sheet_name)
}
writeData(wb, sheet = sheet_name, x = Shel_anova, startCol = 1, startRow = 4, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = left_join(Shel_site_table, Shel_cld_site_table), startCol = 1, startRow = 10, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = Shel_surv_table, startCol = 1, startRow = 21, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = left_join(Shel_int_table, Shel_cld_int_table), startCol = 1, startRow = 26, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = Shel_cld_site_table, startCol = 10, startRow = 10, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = Shel_cld_int_table, startCol = 11, startRow = 26, headerStyle = bold_header_style)
#
#
#
## Dermo Intensity
sheet_name <- "DermoInt"
# Check if the sheet already exists
if (!(sheet_name %in% names(wb))) {
    addWorksheet(wb, sheet_name)
} 
#
writeData(wb, sheet = sheet_name, x = DInt_anova, startCol = 1, startRow = 4, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = left_join(DInt_site_table, DInt_cld_site_table), startCol = 1, startRow = 10, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = DInt_surv_table, startCol = 1, startRow = 20, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = left_join(DInt_int_table, DInt_cld_int_table), startCol = 10, startRow = 20, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = DInt_cld_site_table, startCol = 1, startRow = 37, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = DInt_cld_int_table, startCol = 1, startRow = 47, headerStyle = bold_header_style)
#
#
#
## Dermo Prevalence
sheet_name <- "DermoPrev"
# Check if the sheet already exists
if (!(sheet_name %in% names(wb))) {
    addWorksheet(wb, sheet_name)
} 
#
writeData(wb, sheet = sheet_name, x = DPre_anova, startCol = 1, startRow = 4, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = left_join(DPre_site_table, DPre_cld_site_table), startCol = 1, startRow = 10, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = DPre_surv_table, startCol = 1, startRow = 20, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = left_join(DPre_int_table, DPre_cld_int_table), startCol = 10, startRow = 20, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = DPre_cld_site_table, startCol = 1, startRow = 37, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = DPre_cld_int_table, startCol = 1, startRow = 47, headerStyle = bold_header_style)
#
#
## Recruitment
sheet_name <- "Rcrt"
# Check if the sheet already exists
if (!(sheet_name %in% names(wb))) {
    addWorksheet(wb, sheet_name)
}
writeData(wb, sheet = sheet_name, x = Rcrt_anova, startCol = 1, startRow = 4, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = left_join(Rcrt_site_table, Rcrt_cld_site_table), startCol = 1, startRow = 10, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = Rcrt_surv_table, startCol = 1, startRow = 20, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = left_join(Rcrt_int_table, Rcrt_cld_int_table), startCol = 10, startRow = 20, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = Rcrt_cld_site_table, startCol = 1, startRow = 37, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = Rcrt_cld_int_table, startCol = 1, startRow = 47, headerStyle = bold_header_style)
#
#
## Salinity
sheet_name <- "Salinity"
# Check if the sheet already exists
if (!(sheet_name %in% names(wb))) {
    addWorksheet(wb, sheet_name)
}
writeData(wb, sheet = sheet_name, x = Sali_anova, startCol = 1, startRow = 4, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = left_join(Sali_site_table, Sali_cld_site_table), startCol = 1, startRow = 10, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = Sali_surv_table, startCol = 1, startRow = 20, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = left_join(Sali_int_table, Sali_cld_int_table), startCol = 10, startRow = 20, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = Sali_cld_site_table, startCol = 1, startRow = 37, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = Sali_cld_int_table, startCol = 1, startRow = 47, headerStyle = bold_header_style)
#
#
## Flow
sheet_name <- "Flow"
# Check if the sheet already exists
if (!(sheet_name %in% names(wb))) {
    addWorksheet(wb, sheet_name)
}
writeData(wb, sheet = sheet_name, x = Flow_anova, startCol = 1, startRow = 4, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = left_join(Flow_site_table, Flow_cld_site_table), startCol = 1, startRow = 10, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = left_join(Flow_surv_table, Flow_cld_year_table), startCol = 1, startRow = 17, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = left_join(Flow_int_table, Flow_cld_int_table), startCol = 12, startRow = 17, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = Flow_cld_site_table, startCol = 1, startRow = 43, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = Flow_cld_year_table, startCol = 1, startRow = 49, headerStyle = bold_header_style)
writeData(wb, sheet = sheet_name, x = Flow_cld_int_table, startCol = 6, startRow = 43, headerStyle = bold_header_style)
#
#
#
#
# Save workbook (overwrite = TRUE ensures updates)
saveWorkbook(wb, file_path, overwrite = TRUE)
#
```

```{r model reference, include = FALSE}
#
## Survey: base_formula <- Live ~ Site * SurvCode
rand_structs <- list(
  none = ~ 0, #model_none <- glmmTMB(Live ~ Site * SurvCode, family = nbinom2, data = Counts2)
  station = ~ (1 | Site/Station), #model_station <- glmmTMB(Live ~ Site * SurvCode + (1 | Site/Station), family = nbinom2, data = Counts2)
  ar1 = ~ ar1(SurvCode + 0 | Site:Station), #model_ar1 <- glmmTMB(Live ~ Site * SurvCode + ar1(SurvCode + 0 |Site:Station), family = nbinom2, data = Counts2)
  both = ~ (1 | Site/Station) + ar1(SurvCode + 0 | Site:Station), #model_both <- glmmTMB(Live ~ Site * SurvCode + (1 | Site/Station) + ar1(SurvCode + 0 | Site:Station), family = nbinom2, data = Counts2)
  extra = ~ Site * SurvCode + (1 + SurvCode|Site/Station) #model_extra <- glmmTMB(Live ~ Site * SurvCode +    (1 + SurvCode | Site/Station), family = nbinom2, data = Counts2)
)
#
#
#
### Dermo Intensity
# random structure formulas
rand_structs_D <- list(
  none = ~ 0,
  station = ~ (1 | Site/Station),
  ar1 = ~ ar1(time + 0 | Site:Station),
  both = ~ (1 | Site/Station) + ar1(time + 0 | Site:Station)
)
#
#

```