---
title: "Survey_Report"
---
# Perform basic analyses, output figures and tables for Survey data

``` {r BasicStats}
### Limit data to March through June samples to reduce seasonal bias
ShellHeights_1 <- ShellHeights_ALL %>%
  filter(month(TripDate) > 02 & month(TripDate) < 07)

Quadrats_1 <- Quadrats_ALL %>%
  filter(month(TripDate) > 02 & month(TripDate) < 07)

### Provides how many were measured for each size class for each quadrat
SHMeasures <- ShellHeights_1 %>%
  group_by(QuadratID) %>%
  summarize(TotalNumMeasured = sum(!is.na(ShellHeight)),
            Count_Spat_1_to_30 = sum(ifelse(ShellHeight >= 1 & ShellHeight <= 30, 1, 0), na.rm = TRUE),
            Count_Seed_31_to_75 = sum(ifelse(ShellHeight >= 31 & ShellHeight <= 75, 1, 0), na.rm = TRUE),
            Count_Legal_76_plus = sum(ifelse(ShellHeight >= 76, 1, 0), na.rm = TRUE)
  )

### Provide stats for how many live oysters there were in each quadrat, by size class
QuadStats <- left_join(Quadrats_1, SHMeasures, by = c("QuadratID")) %>%
  mutate(
    Num_Spat_1_to_30 = if_else(TotalNumMeasured == 0, 0, (Count_Spat_1_to_30 * NumLive) / TotalNumMeasured),
    Num_Seed_31_to_75 = if_else(TotalNumMeasured == 0, 0, (Count_Seed_31_to_75 * NumLive) / TotalNumMeasured),
    Num_Legal_76_plus = if_else(TotalNumMeasured == 0, 0, (Count_Legal_76_plus * NumLive) / TotalNumMeasured),
    LiveDeadRatio = ifelse(is.null(NumLive) | is.null(NumDead) | is.na(NumLive) | is.na(NumDead) | (NumLive + NumDead == 0), 
                           0,
                           NumDead / (NumLive + NumDead))) %>%
  select(-starts_with("Count_")) # Remove Count columns as they are no longer needed

# remove intermediate data frames
# rm(ShellHeights_ALL, ShellHeights_1, Quadrats_ALL, Quadrats_1)

```

``` {r OysterStats}

### Stats for Total Oyster Density and Total Weight Density by Year and ProjectGroup
QuadStats_ALL_Oys1 <- QuadStats %>%
  group_by(Year, 
           ProjectGroup,
           SectionName) %>%
  summarise_ALL() %>%
  arrange(Year,
          ProjectGroup,
          SectionName)

  # Median values
QuadStats_ALL_Oys1median <- QuadStats_ALL_Oys1 %>%
  filter(Year != ReportYear) %>%
  group_by(ProjectGroup) %>%
  summarise(OysterDensityMedian = median(OysterDensityMean, na.rm = TRUE),
              LiveDeadRatioMedian = median(LiveDeadRatioMean, na.rm = TRUE),
              DrillDensityMedian = median(DrillDensityMean, na.rm = TRUE),
              WeightDensityMedian = median(WeightDensityMean, na.rm = TRUE))

# Stats for Total Oyster Density and Total Weight Density by Year and Section
QuadStats_ALL_Oys4 <- QuadStats %>%
  group_by(Year, 
           SectionName) %>%
  summarise_ALL() %>%
  arrange(Year, 
          SectionName)

  # Median values
QuadStats_ALL_Oys4median <- QuadStats_ALL_Oys4 %>%
  filter(Year != ReportYear) %>%
  group_by(SectionName) %>%
  summarise(OysterDensityMedian = median(OysterDensityMean, na.rm = TRUE),
              LiveDeadRatioMedian = median(LiveDeadRatioMean, na.rm = TRUE),
              DrillDensityMedian = median(DrillDensityMean, na.rm = TRUE),
              WeightDensityMedian = median(WeightDensityMean, na.rm = TRUE))

# Prep data frame for creating SH distribution histogram
ShellHeightsReportYrX <- ShellHeights_1 %>%
  filter(!is.na(ShellHeight),
  Year == ReportYear) %>%

  mutate(ShellHeightBin = cut(ShellHeight, 
                              breaks = seq(0, ceiling(max(ShellHeight, na.rm = TRUE)) + 5, by = 5),
                              right = TRUE,
                              include.lowest = TRUE)) %>% # puts measures in 5 mm bins
  group_by(ProjectGroup) %>%
  mutate(ProjectTotal = n()) %>%
  group_by(ProjectGroup, ShellHeightBin, ProjectTotal) %>%
  summarise(ProjectNumberMeasured = n()) %>%
  mutate(PercentMeasured = (ProjectNumberMeasured / ProjectTotal) * 100)

ShellHeightsReportYr <- ShellHeights_1 %>%
  filter(Year == ReportYear) 

maxSH <- max(ShellHeightsReportYr$ShellHeight, na.rm = TRUE)

```

``` {r Survey Figures}

### Function explanation
# generate_plot(df, 
#               x_variable, x_label, 
#               y_variable, y_label, y_SD, 
#               UseColor, UseFill, 
#               title)

# Stats for Total Oyster Density and Total Weight Density by Year and ProjectGroup
# Oysters
QuadStats_ALL_Oys1_fig <- generate_grouped_plot(QuadStats_ALL_Oys1, 
                                                "Year", "Year", 
                                                "OysterDensityMean", "Live oysters / m2)", "OysterDensitySD", 
                                                "ProjectGroup", "ProjectGroup", 
                                                "AB Oyster Density by Year and ProjectGroup")
print(QuadStats_ALL_Oys1_fig)



############################
###############Creating Survey figures per section for better customization
# Creates data frames for each section in each estuary by listing the variations and looping through those variations
# lv1 <- c("AB_W", "AB_C", "AB_E")
# lv2 <- list("AB", "AB", "AB")
lv3 <- c("W", "C", "E")
lv4 <- c("AB West", "AB Central", "AB East") # creates list of section
survey_plot_list <- list() # creates empty to list to store output

  
  

for (i in seq_along(lv3)) {
  df_source <- QuadStats_ALL_Oys1 %>%
    filter(SectionName == lv3[i] & ProjectGroup == "NFWF-2021")

  max_upper <- max(df_source$OysterDensityMean, na.rm = TRUE)
  
   # Create a complete grid for all years for this section
  df_complete <- expand_grid(Year = Years_Survey, SectionName = lv3[i]) %>%
    left_join(df_source, by = c("Year", "SectionName")) %>% 
    mutate(has_data = !is.na(OysterDensityMean)) # Add a flag for missing data
  
    # Define bar width (controls shading width too)
  bar_width <- 0.8
  
  survey_plot_list[[i]] <- df_complete %>% 
  ggplot(aes(x = Year, 
             y = OysterDensityMean, 
             fill = factor(SectionName))) + 

        # --- Bars for months with data ---
    geom_bar(
      data = subset(df_complete, has_data),
      aes(y = OysterDensityMean, fill = factor(SectionName)),
      stat = "identity", color = "black", width = bar_width
    ) +
        
    # --- Light shading for months with no data ---
    geom_rect(
      data = subset(df_complete, !has_data),
      aes(xmin = Year - bar_width / 2,
          xmax = Year + bar_width / 2,
          ymin = 0,
          ymax = ceiling(max_upper)),
      fill = "grey10", color = NA, inherit.aes = FALSE
    ) +
    
    # Add symbol for years with no data
    geom_point(
      data = subset(df_complete, !has_data),
      aes(x = Year),
      y = ceiling(max_upper * 0.25),  # constant numeric
      shape = 4,   # X shape
      size = 4,
      stroke = 1.3,
      color = "black"
    ) +
      
  scale_x_continuous("Year", 
                     breaks = Years_Survey,
                     labels = Years_Survey,
                     expand = c(0.005, 0)) +
  scale_y_continuous("oyster per square meter", expand = c(0, 0),
                     limits = c(0, ceiling(max_upper * 1.1)), #Provides a 5% buffer to the top of bars
                     breaks = pretty(c(0, max_upper))) + 
  ggtitle(lv4[i]) + 
  BaseForm 
}
# You can access individual plots using survey_plot_list[[i]]. For example: print(survey_plot_list[1])
# print(survey_plot_list[[1]])
print(survey_plot_list)
print(survey_plot_list[[1]])
print(survey_plot_list[[2]])
print(survey_plot_list[[3]])













### Size Distributions
# Histograms

histogramX <- ggplot(ShellHeightsReportYrX, aes(x = ShellHeightBin, y = PercentMeasured, fill = ProjectGroup)) +
  geom_col() +
  facet_wrap(~ ProjectGroup) +
  scale_x_discrete(
    breaks = levels(ShellHeightsReportYrX$ShellHeightBin)[seq(1, length(levels(ShellHeightsReportYrX$ShellHeightBin)), by = 3)]
  ) +
  labs(title = paste0("Shell Height Distribution of Oysters Measured During ", ReportYear, " Survey"), 
       x = "Shell Height (mm)", 
       y = "Percent of Measurements Within Groups")  +
  BaseForm +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

histogramX

histogramY <- ggplot(ShellHeightsReportYrX, aes(x = ShellHeightBin, y = PercentMeasured, fill = ProjectGroup)) +
  geom_col() +
  facet_wrap(~ ProjectGroup, ncol = 1, scales = "free_y") +
  scale_x_discrete(
    breaks = levels(ShellHeightsReportYrX$ShellHeightBin)[seq(1, length(levels(ShellHeightsReportYrX$ShellHeightBin)), by = 3)]
  ) +
  labs(title = paste0("Shell Height Distribution of Oysters Measured During ", ReportYear, " Survey"), 
       x = "Shell Height (mm)", 
       y = "Percent of Measurements Within Groups")  +
  BaseForm +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

histogramY


```


```{r ABSurveyFigs, warning = FALSE, message = FALSE, fig.cap = "Figure X. Annual mean density (± S.D.) of ALL oysters recorded at stations in the West, Central, and East sections of Apalachicola Bay over the past fifteen months (five quarters). "}
survey_plot_list[[1]] + rremove('x.text') + theme(plot.margin = unit(c(0,0.2,-0.5,0.1), "lines")) +
survey_plot_list[[2]] + rremove('x.text')+ theme(plot.margin = unit(c(-0.5,0.2,-0.5,0.1), "lines")) +
survey_plot_list[[3]] + theme(plot.margin = unit(c(-0.5,0.2,-0.5,0.1), "lines")) +
plot_layout(ncol = 1)
```



``` {Survey Text}
### Placeholder for Survey text for report
```
This is text to output for Survey

