---
title: "ConditionIndex"
output: html_document
---

# Perform basic analyses, output figures and tables for ConditionIndex data

``` {r BasicStats}

### Stats for ConditionIndex rates
# ConditionIndex by section
ConditionIndexStats <- ConditionIndex %>%
  filter(!is.na(TissueDryWeight),
         !is.na(TarePanWeight),
         !is.na(ShellDryWeight)) %>%
  mutate(Month = month(TripDate),
         Year = year(TripDate),
         CI = ((TissueDryWeight - TarePanWeight) / ShellDryWeight) * 100
         ) %>%
  filter(Year <= ReportYear) 
# filter(CI > 0) %>% # these are initially used filters, We've since gone back and reviewed data that triggered these and dropped them from the database
# filter(!is.na(CI)) 

```

``` {r Condition Index Model Selection, eval = FALSE}
###### ~~~~~~~ DO NOT RUN ~~~~~~~~~~
# Selecting the best fit model
# view the histogram
hist(ConditionIndexStats$CI)

### identify correct distribution
m_gamma <- glmmTMB(CI ~ 1,
  data = ConditionIndexStats,
  family = Gamma(link = "log"))
m_gaussian <- glmmTMB(CI ~ 1,
  data = ConditionIndexStats,
  family = gaussian(link = "identity"))
m_lognormal <- glmmTMB(CI ~ 1,
  data = ConditionIndexStats,
  family = gaussian(link = "log"))

AIC(m_gamma, m_gaussian, m_lognormal)
simulateResiduals(m_gamma, plot = TRUE)
simulateResiduals(m_gaussian, plot = TRUE)
simulateResiduals(m_lognormal, plot = TRUE)
# Best fit identified as Gamma
# DHARMA residuals for gaussian and lognormal looked very similar, not quite fitting the Expected-observed line, dispersion test p = 0.968, outlier test p=0 and Within-group deviations from uniformity significant. Gamma looked better, with a good looking fit along Expected-Observed line, dispersion test p = 0, outlier test p = 0.20616, and Within-group deviations from uniformity significant.

### Adding in Random effect
m0 <- glmmTMB(CI ~ 1,
  data = ConditionIndexStats,
  family = Gamma(link = "log"))
m1 <- glmmTMB(CI ~ 1 + (1 | FixedLocationID),
  data = ConditionIndexStats,
  family = Gamma(link = "log"))

AIC(m0, m1)
VarCorr(m1)
# AIC decreased 245 which is strong evidence for random effect of fixedlovationID
res_m1 <- simulateResiduals(m1)
plot(res_m1)
testDispersion(res_m1)
testOutliers(res_m1)
testUniformity(res_m1)

# Identified that 0016 only has 2 observations, which might affect dispersion
summary(m1)
res_m1 <- simulateResiduals(m1)
testDispersion(res_m1)
testUniformity(res_m1)
plotResiduals(res_m1, form = ConditionIndexStats$FixedLocationID)
plotResiduals(res_m1, form = ConditionIndexStats$CI)

# tested the model without 0016 and found it doesn't affect the values very much, so we will leave it in.
m1_no0016 <- glmmTMB(CI ~ 1 + (1 | FixedLocationID),
  data = subset(ConditionIndexStats, FixedLocationID != "0016"),
  family = Gamma(link = "log"))
AIC(m1, m1_no0016)
VarCorr(m1_no0016)

### Adding in Fixed effects
m2 <- glmmTMB(CI ~ SectionName + (1 | FixedLocationID),
  data = ConditionIndexStats,
  family = Gamma(link = "log"))
model.sel(m1, m2)
simulateResiduals(m2, plot = TRUE)
# SectionName doesn't help
m3 <- glmmTMB(CI ~ factor(Month) + (1 | FixedLocationID),
  data = ConditionIndexStats,
  family = Gamma(link = "log"))
model.sel(m1, m3)
simulateResiduals(m3, plot = TRUE)
# Month helps

# Adding Year
m_year <- glmmTMB(  CI ~ factor(Month) + factor(Year) + (1 | FixedLocationID),
  data = ConditionIndexStats,
  family = Gamma(link = "log"))

AIC(m3, m_year)
summary(m_year)
simulateResiduals(m_year, plot = TRUE)
res_year <- simulateResiduals(m_year)

plot(res_year)
testDispersion(res_year)
testOutliers(res_year)
testUniformity(res_year)
# Year improves fit

plotResiduals(res_year, form = ConditionIndexStats$Month)
plotResiduals(res_year, form = ConditionIndexStats$Year)
plotResiduals(res_year)

# adding Year Month interaction
m_month_year <- glmmTMB(CI ~ factor(Month) * factor(Year) + (1 | FixedLocationID),
  data = ConditionIndexStats,
  family = Gamma(link = "log"))

AIC(m_year, m_month_year)
# Month Year INTERACTION adds too much complexity and not enough improvement of fit

# Use cyclic smoothing of month
m_year_smooth <- glmmTMB(CI ~ s(Month, bs = "cc") + factor(Year) + (1 | FixedLocationID),
  data = ConditionIndexStats,
  family = Gamma(link = "log"))
AIC(m_year, m_year_smooth)
summary(m_year_smooth)
simulateResiduals(m_year_smooth, plot = TRUE)
res_year_smooth <- simulateResiduals(m_year_smooth)

plot(res_year_smooth)
testDispersion(res_year_smooth)
testOutliers(res_year_smooth)
testUniformity(res_year_smooth)
# Did not improve fit

# adding dispersion for month and year
m_month_dispersion <- glmmTMB(  CI ~ factor(Month) + factor(Year) + (1 | FixedLocationID),
  data = ConditionIndexStats,
  dispformula = ~ factor(Month),
  family = Gamma(link = "log"))
m_year_dispersion <- glmmTMB(  CI ~ factor(Month) + factor(Year) + (1 | FixedLocationID),
  data = ConditionIndexStats,
  dispformula = ~ factor(Year),
  family = Gamma(link = "log"))

AIC(m_year, m_month_dispersion, m_year_dispersion)
simulateResiduals(m_month_dispersion, plot = TRUE)
simulateResiduals(m_year_dispersion, plot = TRUE)
# Both improved AIC, but worse residuals


```

```{r Condition Index}
# Condition Index model
ConditionIndex <- glmmTMB( 
  CI ~ factor(Month) + factor(Year) + (1 | FixedLocationID),
  family = Gamma(link = "log"),
  data = ConditionIndexStats)

hist(ConditionIndexStats$CI)
simulateResiduals(ConditionIndex, n = 1000, refit = FALSE, plot = TRUE)
acf(residuals(ConditionIndex, type = "pearson"))
r2(ConditionIndex)
summary(ConditionIndex)
# Diagnostics show a satisfactory model fit. The KS test is sensitive to small changes when the number of observations is above 1,000, thus it is not surprising it fails with nearly 8,000 observations in the data. Similarly, a few outliers have caused the Outlier test to fail. Quantile deviations are significant, again likely due to outliers. The ACF Pearson plot shows no significant autocorrelation, implying that the model has effectively captured the temporal dependencies. Despite minor issues, the model represents a good fit for the data. 


# Diagnostic Table for the Appendix
diagnostics_CI_table <- extract_diagnostics(ConditionIndex,  "Condition Index")
kable(diagnostics_CI_table, digits = 3)


# Predict standardized monthly mean condition index
# Rate units are dimensionless

#1. Predicted Means + 95% CI for All Months
# Make sure Month, are factors
emm_month <- emmeans(
  ConditionIndex,
  specs = ~ Month,
  type = "response") %>%
  as.data.frame(emm_month) %>%
  rename(ConditionIndexMean_modeled = response,
         ConditionIndexLower_modeled = asymp.LCL,
         ConditionIndexUpper_modeled = asymp.UCL) %>%
  select(-SE, -df)


#2. Predicted Means + 95% CI for All Years
# Make sure Month, are factors
emm_year <- emmeans(
  ConditionIndex,
  specs = ~ Year,
  type = "response") %>%
  as.data.frame(emm_year) %>%
  rename(ConditionIndexMean_modeled = response,
         ConditionIndexLower_modeled = asymp.LCL,
         ConditionIndexUpper_modeled = asymp.UCL) %>%
  select(-SE, -df) 

############# Raw means and SD
# Months
CI_Month_Raw <- ConditionIndexStats %>%
  group_by(Month) %>%
  summarise(CIMean_Raw = mean(CI, na.rm = TRUE),
            CISD_Raw = sd(CI, na.rm = TRUE),
            .groups = "drop")

# Years
CI_Year_Raw <- ConditionIndexStats %>%
  group_by(Year) %>%
  summarise(CIMean_Raw = mean(CI, na.rm = TRUE),
            CISD_Raw = sd(CI, na.rm = TRUE),
            .groups = "drop")

# Summary Table for Appendix
ConditionIndexMonth_TABLE <- left_join(CI_Month_Raw, emm_month, by = c("Month"))
kable(ConditionIndexMonth_TABLE,
      digits = 1,
      col.names = c("Month", 
      "Raw Mean Condition Index", "Raw SD",
      "Modeled Mean Condition Index", "LCL 95%", "UCL 95%"),
      caption = "Raw and Modeled Mean Condition Index by Month. Condition Index is a dimensionless value. SD = Standard Deviation. LCL = Lower Confidence Limit. UCL = Upper Confidence Limit. ")

ConditionIndexYear_TABLE <- left_join(CI_Year_Raw, emm_year, by = c("Year"))
kable(ConditionIndexYear_TABLE,
      digits = 1,
      col.names = c("Year", 
      "Raw Mean Condition Index", "Raw SD",
      "Modeled Mean Condition Index", "LCL 95%", "UCL 95%"),
      caption = "Raw and Modeled Mean Condition Index by Year Condition Index is a dimensionless value. SD = Standard Deviation. LCL = Lower Confidence Limit. UCL = Upper Confidence Limit. ")

```



``` {r ConditionIndex Figures}
# Month
# ggplot Skeleton
ConditionIndexMonth_FIGURE <-
ggplot() +
  # 1. Line
  geom_line(
    data = emm_month,
    aes(
      x = Month,
      y = ConditionIndexMean_modeled
    ),
    linewidth = 1.2
  ) +
  # 2. mean as a symbol
    geom_point(
    data = emm_month,
    aes(
      x = Month,
      y = ConditionIndexMean_modeled
    ),
    shape = 1,        # open circle
    size = 3,
    stroke = 1
  ) +
  # 4. 95% CI
  geom_errorbar(
    data = emm_month,
    aes(
      x = Month,
      ymin = ConditionIndexLower_modeled,
      ymax = ConditionIndexUpper_modeled
    ),
    width = 0.2,
    linewidth = 0.6
  ) +
  # Scale
  scale_x_continuous(
    breaks = 1:12,
    labels = month.abb
  ) +
  coord_cartesian(ylim = c(1.5, 4.1)) +
  # labels
  labs(
    x = "Month",
    y = "Mean Condition Index",
    title = "Monthly Mean Condition Index"
  ) +

  theme_bw() 

print(ConditionIndexMonth_FIGURE)  
  
######
# Year
# ggplot Skeleton
ConditionIndexYear_FIGURE <-
ggplot() +
  # 1. Line
  geom_line(
    data = emm_year,
    aes(
      x = as.factor(Year),
      y = ConditionIndexMean_modeled,
      group = 1
    ),
    linewidth = 1.2
  ) +
  # 2. mean as a symbol
    geom_point(
    data = emm_year,
    aes(
      x = as.factor(Year),
      y = ConditionIndexMean_modeled
    ),
    shape = 1,        # open circle
    size = 3,
    stroke = 1
  ) +
  # 4. 95% CI
  geom_errorbar(
    data = emm_year,
    aes(
      x = as.factor(Year),
      ymin = ConditionIndexLower_modeled,
      ymax = ConditionIndexUpper_modeled
    ),
    width = 0.2,
    linewidth = 0.6
  ) +
  # Scale
  scale_x_discrete() +
  coord_cartesian(ylim = c(1.5, 4.1)) +

  # labels
  labs(
    x = "Year",
    y = "Mean Condition Index",
    title = "Yearly Mean Condition Index"
  ) +

  theme_bw() 

print(ConditionIndexYear_FIGURE) 

```

``` {ConditionIndex Text}
### Placeholder for ConditionIndex text for report
```
This is text to output for ConditionIndex
